#!/usr/bin/env python3
"""
================================================================================
  NIDS ROBUSTNESS AUDIT (STRESS-TESTING) WITH GAN-GENERATED ADVERSARIAL TRAFFIC
================================================================================

  This script trains standard NIDS classifiers on REAL data and evaluates them
  against extreme adversarial scenarios generated by WGAN-GP models.

  Unlike previous experiments (TSTR), here the GANs are NOT used for training.
  Instead, they generate adversarial test sets to probe the robustness of
  production-grade classifiers.
================================================================================
"""

import os
import sys
import json
import pickle
import argparse
import warnings
import math
import numpy as np
import pandas as pd
import polars as pl
from datetime import datetime
from collections import Counter

from sklearn.preprocessing import MinMaxScaler, LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    classification_report, confusion_matrix,
    accuracy_score, f1_score, precision_score, recall_score
)
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from lightgbm import LGBMClassifier
from xgboost import XGBClassifier

import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import seaborn as sns

import tensorflow as tf
from tensorflow.keras.models import load_model

warnings.filterwarnings('ignore')
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'

# =============================================================================
# CONFIGURATION - Update these paths to match your environment
# =============================================================================

REAL_DATA_PATH = '<PATH_TO_CICIDS2017_CSV>'
MODELS_DIR = '<PATH_TO_WGAN_MODELS_DIR>'
OUTPUT_DIR = '<PATH_TO_RESULTS_STRESS_TEST>'
RANDOM_STATE = 42
LATENT_DIM = 100

# All 7 classes in the CIC-IDS2017 dataset
ALL_CLASSES = ['BENIGN', 'Bot', 'Brute Force', 'DDoS', 'DoS', 'Port Scan', 'Web Attack']

# Binary classification: BENIGN vs ATTACK
BINARY_CLASSES = ['BENIGN', 'ATTACK']

CLASS_TO_FOLDER = {
    'BENIGN': 'benign',
    'Bot': 'bot',
    'Brute Force': 'brute_force',
    'DDoS': 'ddos',
    'DoS': 'dos',
    'Port Scan': 'port_scan',
    'Web Attack': 'web_attack',
}

FEATURES_BASE = [
    'Source Port', 'Destination Port', 'Protocol',
    'Total Fwd Packets', 'Total Backward Packets',
    'Total Length of Fwd Packets', 'Total Length of Bwd Packets',
    'Flow Duration', 'Flow IAT Mean', 'Flow IAT Std',
    'Fwd IAT Mean', 'Bwd IAT Mean',
    'Fwd Packet Length Mean', 'Bwd Packet Length Mean',
    'Packet Length Std', 'Max Packet Length',
    'SYN Flag Count', 'ACK Flag Count', 'FIN Flag Count',
    'RST Flag Count', 'PSH Flag Count'
]

FEATURE_NAMES = FEATURES_BASE + [
    'Src_IP_1', 'Src_IP_2', 'Src_IP_3', 'Src_IP_4',
    'Dst_IP_1', 'Dst_IP_2', 'Dst_IP_3', 'Dst_IP_4'
]

LOG_COLUMNS = [
    'Total Fwd Packets', 'Total Backward Packets',
    'Total Length of Fwd Packets', 'Total Length of Bwd Packets',
    'Flow Duration', 'Flow IAT Mean', 'Flow IAT Std',
    'Fwd IAT Mean', 'Bwd IAT Mean',
    'Fwd Packet Length Mean', 'Bwd Packet Length Mean',
    'Packet Length Std', 'Max Packet Length'
]

# =============================================================================
# STRESS-TEST SCENARIOS
# =============================================================================
STRESS_SCENARIOS = {
    'Scenario_A': {
        'name': 'Baseline Equilibrado',
        'description': 'Balanced baseline: 10k benign, 2k each attack',
        'distribution': {
            'BENIGN': 10000,
            'Bot': 2000,
            'Brute Force': 2000,
            'DDoS': 2000,
            'DoS': 2000,
            'Port Scan': 2000,
            'Web Attack': 2000,
        }
    },
    'Scenario_B': {
        'name': 'Botnet Storm',
        'description': 'Massive botnet attack: 50k Bots, 5k Benign, 0 rest',
        'distribution': {
            'BENIGN': 5000,
            'Bot': 50000,
        }
    },
    'Scenario_C': {
        'name': 'DDoS Flood',
        'description': 'Volumetric saturation: 40k DDoS + 40k DoS + 5k Benign',
        'distribution': {
            'BENIGN': 5000,
            'DDoS': 40000,
            'DoS': 40000,
        }
    },
    'Scenario_D': {
        'name': 'Inverse Imbalance (Pesadilla)',
        'description': 'Nightmare: 1k Benign, 10k each attack. Malicious >90%',
        'distribution': {
            'BENIGN': 1000,
            'Bot': 10000,
            'Brute Force': 10000,
            'DDoS': 10000,
            'DoS': 10000,
            'Port Scan': 10000,
            'Web Attack': 10000,
        }
    },
}

# =============================================================================
# VICTIM MODELS
# =============================================================================
VICTIM_MODELS = {
    'LogisticReg': lambda: LogisticRegression(
        max_iter=1000,
        n_jobs=-1, random_state=RANDOM_STATE,
        class_weight='balanced', solver='lbfgs'
    ),
    'RandomForest': lambda: RandomForestClassifier(
        n_estimators=200, random_state=RANDOM_STATE,
        n_jobs=-1, class_weight='balanced_subsample'
    ),
    'KNeighbors': lambda: KNeighborsClassifier(
        n_neighbors=5, n_jobs=-1
    ),
    'LightGBM': lambda: LGBMClassifier(
        n_estimators=200, random_state=RANDOM_STATE,
        n_jobs=-1, verbose=-1, class_weight='balanced'
    ),
    'XGBoost': lambda: XGBClassifier(
        n_estimators=200, random_state=RANDOM_STATE,
        n_jobs=-1, verbosity=0, use_label_encoder=False,
        eval_metric='mlogloss'
    ),
}


# =============================================================================
# UTILITY FUNCTIONS
# =============================================================================

def convert_to_binary_labels(y_multiclass, label_encoder_multi):
    """Convert multiclass encoded labels to binary (0=BENIGN, 1=ATTACK)."""
    class_names = label_encoder_multi.inverse_transform(y_multiclass)
    y_binary = np.where(class_names == 'BENIGN', 0, 1)
    return y_binary


def convert_scenario_to_binary(df_scenario):
    """Convert scenario DataFrame labels to binary."""
    df = df_scenario.copy()
    df['Label_Class'] = df['Label_Class'].apply(lambda x: 'BENIGN' if x == 'BENIGN' else 'ATTACK')
    return df


def print_header():
    print("=" * 100)
    print("  NIDS ROBUSTNESS AUDIT - STRESS TESTING WITH GAN-GENERATED TRAFFIC")
    print("  Train on Real Data -> Test on Adversarial Scenarios")
    print("  Modes: MULTICLASS (7 classes) + BINARY (Benign vs Attack)")
    print("=" * 100)
    print(f"  Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    print(f"  Random State: {RANDOM_STATE}")
    print("=" * 100)


def load_real_data():
    """Load the CIC-IDS2017 dataset."""
    print("\n" + "=" * 70)
    print("[PHASE 0] LOADING REAL DATA")
    print("=" * 70)

    file_size = os.path.getsize(REAL_DATA_PATH)
    print(f"  File: {REAL_DATA_PATH}")
    print(f"  Size: {file_size / (1024 * 1024):.2f} MB")

    start_time = datetime.now()
    df_pl = pl.read_csv(REAL_DATA_PATH, low_memory=False)
    df = df_pl.to_pandas()
    df.columns = df.columns.str.strip()
    print(f"  Loaded in {datetime.now() - start_time}")
    print(f"  Total records: {len(df):,}")

    return df


def prepare_features(df: pd.DataFrame, target_classes=None) -> pd.DataFrame:
    """Prepare feature matrix from raw CIC-IDS2017 data."""
    df = df.copy()

    label_col = 'Attack Type' if 'Attack Type' in df.columns else 'Label'
    df['Label_Class'] = df[label_col]

    if target_classes is not None:
        df = df[df['Label_Class'].isin(target_classes)].copy()

    features_df = df[FEATURES_BASE].copy()

    if 'Source IP' in df.columns:
        octets = df['Source IP'].astype(str).str.split('.', expand=True)
        for i in range(4):
            features_df[f'Src_IP_{i+1}'] = pd.to_numeric(octets[i], errors='coerce').fillna(0).astype(int)
    else:
        for i in range(4):
            features_df[f'Src_IP_{i+1}'] = 0

    if 'Destination IP' in df.columns:
        octets = df['Destination IP'].astype(str).str.split('.', expand=True)
        for i in range(4):
            features_df[f'Dst_IP_{i+1}'] = pd.to_numeric(octets[i], errors='coerce').fillna(0).astype(int)
    else:
        for i in range(4):
            features_df[f'Dst_IP_{i+1}'] = 0

    features_df['Label_Class'] = df['Label_Class'].values

    features_df.replace([np.inf, -np.inf], np.nan, inplace=True)
    features_df.fillna(0, inplace=True)

    return features_df


# =============================================================================
# PHASE 1: TRAIN VICTIM NIDS
# =============================================================================

def train_victim_models(X_train, y_train, scaler, mode='multiclass'):
    """Train all victim NIDS models on real (clean) data."""
    mode_label = mode.upper()
    print("\n" + "=" * 70)
    print(f"[PHASE 1] TRAINING VICTIM NIDS - {mode_label} (Gold Standard)")
    print("=" * 70)
    n_classes = len(np.unique(y_train))
    print(f"  Mode: {mode_label} ({n_classes} classes)")
    print(f"  Training samples: {len(X_train):,}")
    print(f"  Models: {', '.join(VICTIM_MODELS.keys())}")

    X_train_scaled = scaler.transform(X_train)
    X_train_scaled = np.nan_to_num(X_train_scaled, nan=0, posinf=0, neginf=0)

    trained_models = {}
    for name, model_fn in VICTIM_MODELS.items():
        print(f"\n  Training {name} [{mode_label}]...", end=" ", flush=True)
        model = model_fn()
        start_time = datetime.now()
        model.fit(X_train_scaled, y_train)
        elapsed = datetime.now() - start_time
        print(f"Done ({elapsed})")
        trained_models[name] = model

    print(f"\n  [OK] {len(trained_models)} {mode_label} models trained successfully.")
    return trained_models


# =============================================================================
# PHASE 2: GENERATE STRESS SCENARIOS VIA GAN
# =============================================================================

def get_available_generators():
    """Discover available WGAN-GP v2 generators."""
    available = {}
    for class_name, folder in CLASS_TO_FOLDER.items():
        model_path = os.path.join(MODELS_DIR, folder, f'generator_{folder}.h5')
        if os.path.exists(model_path):
            available[class_name] = {
                'folder': folder,
                'model_path': model_path,
                'source_dir': MODELS_DIR,
            }
    return available


def load_scaler_for_class(class_name, source_dir):
    """Load or recreate the MinMaxScaler for a given class."""
    folder = CLASS_TO_FOLDER[class_name]

    search_dirs = [source_dir] if source_dir else [MODELS_DIR]

    for sd in search_dirs:
        if sd is None:
            continue
        scaler_path = os.path.join(sd, folder, 'scaler.pkl')
        if os.path.exists(scaler_path):
            with open(scaler_path, 'rb') as f:
                return pickle.load(f)

    # Fallback: recreate scaler from original dataset
    print(f"    Recreating scaler for {class_name} from original data...")

    df_pl = pl.read_csv(REAL_DATA_PATH, low_memory=False)
    df = df_pl.to_pandas()
    df.columns = df.columns.str.strip()
    df_cls = df[df['Attack Type'] == class_name].copy()

    features = df_cls[FEATURES_BASE].copy()

    octets = df_cls['Source IP'].astype(str).str.split('.', expand=True)
    for i in range(4):
        features[f'Src_IP_{i+1}'] = pd.to_numeric(octets[i], errors='coerce').fillna(0).astype(int)

    octets = df_cls['Destination IP'].astype(str).str.split('.', expand=True)
    for i in range(4):
        features[f'Dst_IP_{i+1}'] = pd.to_numeric(octets[i], errors='coerce').fillna(0).astype(int)

    for col in LOG_COLUMNS:
        features[col] = np.log1p(features[col].clip(lower=0))
        features[col] = features[col].clip(lower=-20, upper=20)

    features.replace([np.inf, -np.inf], np.nan, inplace=True)
    features.fillna(0, inplace=True)

    scaler = MinMaxScaler(feature_range=(-1, 1))
    scaler.fit(features[FEATURE_NAMES])

    scaler_path = os.path.join(source_dir or MODELS_DIR, folder, 'scaler.pkl')
    try:
        with open(scaler_path, 'wb') as f:
            pickle.dump(scaler, f)
    except Exception:
        pass

    return scaler


def generate_gan_samples(generator, n_samples, latent_dim=LATENT_DIM, batch_size=1024):
    """Generate synthetic samples from a WGAN-GP generator."""
    all_samples = []
    remaining = n_samples

    while remaining > 0:
        current_batch = min(batch_size, remaining)
        noise = np.random.normal(0, 1, (current_batch, latent_dim))
        samples = generator.predict(noise, verbose=0)
        all_samples.append(samples)
        remaining -= current_batch

    return np.vstack(all_samples)


def reconstruct_features(X_synthetic, scaler):
    """Inverse-transform GAN output back to original feature space."""
    X_inv = scaler.inverse_transform(X_synthetic)
    df_rec = pd.DataFrame(X_inv, columns=FEATURE_NAMES)

    for col in LOG_COLUMNS:
        df_rec[col] = np.expm1(df_rec[col])

    for col in df_rec.columns:
        if col.startswith('Src_IP_') or col.startswith('Dst_IP_'):
            df_rec[col] = df_rec[col].round().clip(0, 255).astype(int)

    df_rec['Source Port'] = df_rec['Source Port'].round().clip(1, 65535).astype(int)
    df_rec['Destination Port'] = df_rec['Destination Port'].round().clip(1, 65535).astype(int)
    df_rec['Protocol'] = df_rec['Protocol'].round().clip(1, 255).astype(int)

    for col in LOG_COLUMNS + ['SYN Flag Count', 'ACK Flag Count',
                               'FIN Flag Count', 'RST Flag Count', 'PSH Flag Count']:
        df_rec[col] = df_rec[col].clip(lower=0)

    integer_columns = ['Total Fwd Packets', 'Total Backward Packets',
                        'SYN Flag Count', 'ACK Flag Count',
                        'FIN Flag Count', 'RST Flag Count', 'PSH Flag Count']
    for col in integer_columns:
        df_rec[col] = df_rec[col].round().astype(int)

    return df_rec


def generate_stress_scenarios():
    """Generate all stress-test datasets using WGAN-GP v2 models."""
    print("\n" + "=" * 70)
    print("[PHASE 2] GENERATING STRESS-TEST SCENARIOS VIA GAN")
    print("=" * 70)

    available = get_available_generators()
    print(f"\n  Available generators: {len(available)}")
    for cls, info in available.items():
        print(f"    {cls:<15} -> {info['model_path']}")

    scenarios = {}

    for scenario_id, scenario_cfg in STRESS_SCENARIOS.items():
        print(f"\n  {'─' * 60}")
        print(f"  Generating {scenario_id}: {scenario_cfg['name']}")
        print(f"  {scenario_cfg['description']}")
        print(f"  {'─' * 60}")

        distribution = scenario_cfg['distribution']
        parts = []

        for class_name, n_samples in distribution.items():
            if n_samples <= 0:
                continue

            if class_name not in available:
                print(f"    [WARN] No generator for '{class_name}', skipping.")
                continue

            print(f"    {class_name}: generating {n_samples:,} samples...", end=" ", flush=True)

            gen_info = available[class_name]
            generator = load_model(gen_info['model_path'], compile=False)
            gan_scaler = load_scaler_for_class(class_name, gen_info['source_dir'])

            X_synth = generate_gan_samples(generator, n_samples)
            df_synth = reconstruct_features(X_synth, gan_scaler)
            df_synth['Label_Class'] = class_name

            parts.append(df_synth)
            print(f"OK ({len(df_synth):,})")

            del generator
            tf.keras.backend.clear_session()

        if parts:
            df_scenario = pd.concat(parts, ignore_index=True)
            df_scenario = df_scenario.sample(frac=1, random_state=RANDOM_STATE).reset_index(drop=True)
            scenarios[scenario_id] = df_scenario

            total = len(df_scenario)
            print(f"\n    Total {scenario_id}: {total:,} samples")
            for cls in distribution:
                if cls in df_scenario['Label_Class'].values:
                    cnt = len(df_scenario[df_scenario['Label_Class'] == cls])
                    print(f"      {cls:<15}: {cnt:>10,} ({cnt/total*100:>5.1f}%)")

    print(f"\n  [OK] {len(scenarios)} scenarios generated.")
    return scenarios


# =============================================================================
# PHASE 3: MASSIVE EVALUATION
# =============================================================================

def evaluate_model_on_scenario(model, model_name, X_test, y_test,
                                label_encoder, scenario_name, mode='multiclass'):
    """Evaluate a single model on a single scenario."""
    y_pred = model.predict(X_test)

    # Use all encoded class indices so metrics are consistent even when
    # a scenario only contains a subset of classes.
    all_labels = list(range(len(label_encoder.classes_)))

    accuracy = accuracy_score(y_test, y_pred)
    f1_macro = f1_score(y_test, y_pred, average='macro', zero_division=0, labels=all_labels)
    f1_weighted = f1_score(y_test, y_pred, average='weighted', zero_division=0, labels=all_labels)
    precision_macro = precision_score(y_test, y_pred, average='macro', zero_division=0, labels=all_labels)
    recall_macro = recall_score(y_test, y_pred, average='macro', zero_division=0, labels=all_labels)

    report = classification_report(
        y_test, y_pred,
        labels=all_labels,
        target_names=label_encoder.classes_,
        output_dict=True,
        zero_division=0
    )

    cm = confusion_matrix(y_test, y_pred, labels=all_labels)

    return {
        'Model': model_name,
        'Scenario': scenario_name,
        'Mode': mode,
        'Accuracy': accuracy,
        'F1_Macro': f1_macro,
        'F1_Weighted': f1_weighted,
        'Precision_Macro': precision_macro,
        'Recall_Macro': recall_macro,
        'Test_Samples': len(y_test),
        'Report': report,
        'Confusion_Matrix': cm,
    }


def run_massive_evaluation(trained_models, scaler, label_encoder,
                            X_test_real, y_test_real,
                            scenarios, output_dir, mode='multiclass'):
    """Evaluate every model on every scenario (including real baseline)."""
    mode_label = mode.upper()
    print("\n" + "=" * 70)
    print(f"[PHASE 3] MASSIVE EVALUATION - {mode_label}")
    print("=" * 70)

    all_results = []

    # --- Real baseline ---
    print(f"\n  {'━' * 60}")
    print(f"  [{mode_label}] Evaluating on REAL TEST SET (baseline)")
    print(f"  {'━' * 60}")

    X_real_scaled = scaler.transform(X_test_real)
    X_real_scaled = np.nan_to_num(X_real_scaled, nan=0, posinf=0, neginf=0)

    for model_name, model in trained_models.items():
        result = evaluate_model_on_scenario(
            model, model_name, X_real_scaled, y_test_real,
            label_encoder, 'Real_Test', mode=mode
        )
        all_results.append(result)
        print(f"    {model_name:<15} Acc={result['Accuracy']:.4f}  "
              f"F1-M={result['F1_Macro']:.4f}  F1-W={result['F1_Weighted']:.4f}")

    # --- Synthetic stress scenarios ---
    for scenario_id, df_scenario in scenarios.items():
        scenario_name = STRESS_SCENARIOS[scenario_id]['name']
        print(f"\n  {'━' * 60}")
        print(f"  [{mode_label}] Evaluating on {scenario_id}: {scenario_name}")
        print(f"  Samples: {len(df_scenario):,}")
        print(f"  {'━' * 60}")

        # For binary mode, convert labels
        if mode == 'binary':
            df_eval = convert_scenario_to_binary(df_scenario)
        else:
            df_eval = df_scenario.copy()

        # Align features: use only FEATURE_NAMES columns present in df_eval
        feature_cols = [c for c in FEATURE_NAMES if c in df_eval.columns]
        X_scenario = df_eval[feature_cols].values
        X_scenario = np.nan_to_num(X_scenario, nan=0, posinf=0, neginf=0)

        # Encode labels — handle classes not seen during training
        scenario_classes = df_eval['Label_Class'].unique()
        known_classes = set(label_encoder.classes_)
        unknown = set(scenario_classes) - known_classes
        if unknown:
            print(f"    [WARN] Unknown classes in scenario: {unknown}. Skipping those samples.")
            df_eval = df_eval[df_eval['Label_Class'].isin(known_classes)].copy()
            X_scenario = df_eval[feature_cols].values
            X_scenario = np.nan_to_num(X_scenario, nan=0, posinf=0, neginf=0)

        y_scenario = label_encoder.transform(df_eval['Label_Class'])

        X_scenario_scaled = scaler.transform(X_scenario)
        X_scenario_scaled = np.nan_to_num(X_scenario_scaled, nan=0, posinf=0, neginf=0)

        for model_name, model in trained_models.items():
            result = evaluate_model_on_scenario(
                model, model_name, X_scenario_scaled, y_scenario,
                label_encoder, scenario_id, mode=mode
            )
            all_results.append(result)
            print(f"    {model_name:<15} Acc={result['Accuracy']:.4f}  "
                  f"F1-M={result['F1_Macro']:.4f}  F1-W={result['F1_Weighted']:.4f}")

    return all_results


# =============================================================================
# PHASE 4: PAPER-READY VISUALIZATIONS
# =============================================================================

def set_paper_style():
    """Configure matplotlib/seaborn for publication-quality figures."""
    plt.rcParams.update({
        'figure.dpi': 150,
        'savefig.dpi': 300,
        'font.size': 11,
        'axes.titlesize': 13,
        'axes.labelsize': 12,
        'xtick.labelsize': 10,
        'ytick.labelsize': 10,
        'legend.fontsize': 10,
        'figure.figsize': (10, 6),
        'axes.grid': True,
        'grid.alpha': 0.3,
        'axes.spines.top': False,
        'axes.spines.right': False,
    })
    sns.set_theme(style='whitegrid', palette='muted', font_scale=1.1)


def plot_robustness_degradation(all_results, output_dir, mode='multiclass'):
    """
    Graph 1: Grouped bar chart showing F1-Macro degradation per model across scenarios.
    """
    mode_label = mode.upper()
    print(f"\n  Generating Plot 1: Robustness Degradation [{mode_label}]...")

    df_res = pd.DataFrame([{
        'Model': r['Model'],
        'Scenario': r['Scenario'],
        'F1_Macro': r['F1_Macro'],
        'Precision_Macro': r['Precision_Macro'],
        'Recall_Macro': r['Recall_Macro'],
        'Accuracy': r['Accuracy'],
    } for r in all_results])

    # Order scenarios logically
    scenario_order = ['Real_Test', 'Scenario_A', 'Scenario_B', 'Scenario_C', 'Scenario_D']
    scenario_labels = {
        'Real_Test': 'Real Test',
        'Scenario_A': 'A: Balanced',
        'Scenario_B': 'B: Botnet Storm',
        'Scenario_C': 'C: DDoS Flood',
        'Scenario_D': 'D: Nightmare',
    }

    present_scenarios = [s for s in scenario_order if s in df_res['Scenario'].values]
    df_plot = df_res[df_res['Scenario'].isin(present_scenarios)].copy()
    df_plot['Scenario_Label'] = df_plot['Scenario'].map(scenario_labels)

    # --- F1-Macro ---
    fig, axes = plt.subplots(1, 2, figsize=(18, 7))

    scenario_label_order = [scenario_labels[s] for s in present_scenarios]

    ax = axes[0]
    sns.barplot(
        data=df_plot, x='Scenario_Label', y='F1_Macro', hue='Model',
        order=scenario_label_order, ax=ax, edgecolor='black', linewidth=0.5
    )
    ax.set_title(f'F1-Score (Macro) Degradation [{mode_label}]', fontweight='bold')
    ax.set_xlabel('Test Scenario')
    ax.set_ylabel('F1-Score (Macro)')
    ax.set_ylim(0, 1.05)
    ax.legend(title='Model', loc='lower left', framealpha=0.9)

    # Add value labels on bars
    for container in ax.containers:
        ax.bar_label(container, fmt='%.2f', fontsize=7, padding=2, rotation=90)

    # --- Accuracy ---
    ax = axes[1]
    sns.barplot(
        data=df_plot, x='Scenario_Label', y='Accuracy', hue='Model',
        order=scenario_label_order, ax=ax, edgecolor='black', linewidth=0.5
    )
    ax.set_title(f'Accuracy Degradation [{mode_label}]', fontweight='bold')
    ax.set_xlabel('Test Scenario')
    ax.set_ylabel('Accuracy')
    ax.set_ylim(0, 1.05)
    ax.legend(title='Model', loc='lower left', framealpha=0.9)

    for container in ax.containers:
        ax.bar_label(container, fmt='%.2f', fontsize=7, padding=2, rotation=90)

    plt.tight_layout()
    path = os.path.join(output_dir, f'plot1_robustness_degradation_{mode}.png')
    plt.savefig(path, bbox_inches='tight')
    plt.close()
    print(f"    Saved: {path}")

    # --- Heatmap version (compact alternative) ---
    fig, ax = plt.subplots(figsize=(10, 5))
    pivot = df_plot.pivot_table(index='Model', columns='Scenario_Label',
                                 values='F1_Macro', aggfunc='first')
    pivot = pivot[scenario_label_order]
    sns.heatmap(pivot, annot=True, fmt='.3f', cmap='RdYlGn', vmin=0, vmax=1,
                linewidths=0.5, ax=ax, cbar_kws={'label': 'F1-Macro'})
    ax.set_title(f'F1-Macro Heatmap: Model × Scenario [{mode_label}]', fontweight='bold')
    plt.tight_layout()
    path_hm = os.path.join(output_dir, f'plot1b_heatmap_f1macro_{mode}.png')
    plt.savefig(path_hm, bbox_inches='tight')
    plt.close()
    print(f"    Saved: {path_hm}")


def plot_radar_chart(all_results, label_encoder, output_dir, mode='multiclass'):
    """
    Graph 2: Radar / Spider plot for the best model under Scenario D (Nightmare).
    Shows per-class F1-score. Only generated for multiclass mode (binary has only 2 axes).
    """
    mode_label = mode.upper()
    print(f"\n  Generating Plot 2: Radar Chart (Scenario D - Nightmare) [{mode_label}]...")

    if mode == 'binary':
        # For binary, generate a grouped bar chart instead of radar
        results_d = [r for r in all_results if r['Scenario'] == 'Scenario_D']
        if not results_d:
            print("    [SKIP] Scenario D not found.")
            return

        fig, ax = plt.subplots(figsize=(10, 6))
        models = []
        benign_f1 = []
        attack_f1 = []
        for r in results_d:
            models.append(r['Model'])
            benign_f1.append(r['Report'].get('BENIGN', {}).get('f1-score', 0.0))
            attack_f1.append(r['Report'].get('ATTACK', {}).get('f1-score', 0.0))

        x = np.arange(len(models))
        width = 0.35
        ax.bar(x - width/2, benign_f1, width, label='BENIGN', color='#2ecc71', edgecolor='black', linewidth=0.5)
        ax.bar(x + width/2, attack_f1, width, label='ATTACK', color='#e74c3c', edgecolor='black', linewidth=0.5)
        ax.set_xlabel('Model')
        ax.set_ylabel('F1-Score')
        ax.set_title('Per-Class F1-Score Under Scenario D (Nightmare) [BINARY]', fontweight='bold')
        ax.set_xticks(x)
        ax.set_xticklabels(models, rotation=15)
        ax.set_ylim(0, 1.05)
        ax.legend()
        for i, (b, a) in enumerate(zip(benign_f1, attack_f1)):
            ax.text(i - width/2, b + 0.02, f'{b:.3f}', ha='center', fontsize=8)
            ax.text(i + width/2, a + 0.02, f'{a:.3f}', ha='center', fontsize=8)

        plt.tight_layout()
        path = os.path.join(output_dir, 'plot2_binary_f1_scenario_d.png')
        plt.savefig(path, bbox_inches='tight')
        plt.close()
        print(f"    Saved: {path}")
        return

    # Find results for Scenario D
    results_d = [r for r in all_results if r['Scenario'] == 'Scenario_D']
    if not results_d:
        print("    [SKIP] Scenario D not found.")
        return

    # Pick the best model on Scenario D by F1-Macro
    best_d = max(results_d, key=lambda x: x['F1_Macro'])
    print(f"    Best model on Scenario D: {best_d['Model']} (F1-Macro={best_d['F1_Macro']:.4f})")

    # Also show all models on the radar
    report_data = {}
    for r in results_d:
        class_f1 = {}
        for cls_name in label_encoder.classes_:
            if cls_name in r['Report']:
                class_f1[cls_name] = r['Report'][cls_name]['f1-score']
            else:
                class_f1[cls_name] = 0.0
        report_data[r['Model']] = class_f1

    categories = list(label_encoder.classes_)
    N = len(categories)
    angles = [n / float(N) * 2 * math.pi for n in range(N)]
    angles += angles[:1]  # close the polygon

    fig, ax = plt.subplots(figsize=(9, 9), subplot_kw=dict(polar=True))

    colors = plt.cm.Set2(np.linspace(0, 1, len(report_data)))

    for idx, (model_name, class_f1) in enumerate(report_data.items()):
        values = [class_f1.get(cat, 0.0) for cat in categories]
        values += values[:1]

        linewidth = 2.5 if model_name == best_d['Model'] else 1.2
        alpha_fill = 0.15 if model_name == best_d['Model'] else 0.05

        ax.plot(angles, values, 'o-', linewidth=linewidth,
                label=model_name, color=colors[idx])
        ax.fill(angles, values, alpha=alpha_fill, color=colors[idx])

    ax.set_xticks(angles[:-1])
    ax.set_xticklabels(categories, fontsize=10)
    ax.set_ylim(0, 1.0)
    ax.set_yticks([0.2, 0.4, 0.6, 0.8, 1.0])
    ax.set_yticklabels(['0.2', '0.4', '0.6', '0.8', '1.0'], fontsize=8, color='grey')
    ax.set_title('Per-Class F1-Score Under Scenario D (Nightmare)\nAll Models [MULTICLASS]',
                 fontweight='bold', pad=20)
    ax.legend(loc='upper right', bbox_to_anchor=(1.35, 1.1), framealpha=0.9)

    plt.tight_layout()
    path = os.path.join(output_dir, 'plot2_radar_scenario_d_multiclass.png')
    plt.savefig(path, bbox_inches='tight')
    plt.close()
    print(f"    Saved: {path}")


def plot_confusion_matrix_botnet(all_results, label_encoder, output_dir, mode='multiclass'):
    """
    Graph 3: Confusion matrix of the best model under Scenario B (Botnet Storm).
    """
    mode_label = mode.upper()
    print(f"\n  Generating Plot 3: Confusion Matrix (Scenario B - Botnet Storm) [{mode_label}]...")

    results_b = [r for r in all_results if r['Scenario'] == 'Scenario_B']
    if not results_b:
        print("    [SKIP] Scenario B not found.")
        return

    best_b = max(results_b, key=lambda x: x['F1_Macro'])
    print(f"    Best model on Scenario B: {best_b['Model']} (F1-Macro={best_b['F1_Macro']:.4f})")

    cm = best_b['Confusion_Matrix']

    # Determine which classes are actually present in this scenario
    # The CM may have rows/cols for all encoded classes, but only some are present
    class_names = label_encoder.classes_

    fig, axes = plt.subplots(1, 2, figsize=(18, 7))

    # Raw counts
    ax = axes[0]
    sns.heatmap(
        pd.DataFrame(cm, index=class_names, columns=class_names),
        annot=True, fmt='d', cmap='Blues', ax=ax,
        linewidths=0.5, cbar_kws={'label': 'Count'}
    )
    ax.set_title(f'Confusion Matrix (Counts)\n{best_b["Model"]} on Scenario B: Botnet Storm [{mode_label}]',
                 fontweight='bold')
    ax.set_xlabel('Predicted')
    ax.set_ylabel('True')

    # Normalized (recall-based)
    ax = axes[1]
    cm_norm = cm.astype(float)
    row_sums = cm_norm.sum(axis=1, keepdims=True)
    row_sums[row_sums == 0] = 1  # avoid division by zero
    cm_norm = cm_norm / row_sums

    sns.heatmap(
        pd.DataFrame(cm_norm, index=class_names, columns=class_names),
        annot=True, fmt='.2%', cmap='Oranges', ax=ax,
        linewidths=0.5, vmin=0, vmax=1, cbar_kws={'label': 'Rate'}
    )
    ax.set_title(f'Confusion Matrix (Normalized by True Class)\n{best_b["Model"]} on Scenario B: Botnet Storm [{mode_label}]',
                 fontweight='bold')
    ax.set_xlabel('Predicted')
    ax.set_ylabel('True')

    plt.tight_layout()
    path = os.path.join(output_dir, f'plot3_confusion_matrix_botnet_{mode}.png')
    plt.savefig(path, bbox_inches='tight')
    plt.close()
    print(f"    Saved: {path}")

    # Also generate CM for Scenario D (Nightmare) with best overall model
    results_d = [r for r in all_results if r['Scenario'] == 'Scenario_D']
    if results_d:
        best_overall = max(results_d, key=lambda x: x['F1_Macro'])
        cm_d = best_overall['Confusion_Matrix']

        fig, ax = plt.subplots(figsize=(9, 7))
        cm_d_norm = cm_d.astype(float)
        row_sums_d = cm_d_norm.sum(axis=1, keepdims=True)
        row_sums_d[row_sums_d == 0] = 1
        cm_d_norm = cm_d_norm / row_sums_d

        sns.heatmap(
            pd.DataFrame(cm_d_norm, index=class_names, columns=class_names),
            annot=True, fmt='.2%', cmap='Reds', ax=ax,
            linewidths=0.5, vmin=0, vmax=1, cbar_kws={'label': 'Rate'}
        )
        ax.set_title(f'Confusion Matrix (Normalized)\n{best_overall["Model"]} on Scenario D: Nightmare [{mode_label}]',
                     fontweight='bold')
        ax.set_xlabel('Predicted')
        ax.set_ylabel('True')
        plt.tight_layout()
        path_d = os.path.join(output_dir, f'plot3b_confusion_matrix_nightmare_{mode}.png')
        plt.savefig(path_d, bbox_inches='tight')
        plt.close()
        print(f"    Saved: {path_d}")


def _plot_multiclass_vs_binary(results_multi, results_binary, output_dir):
    """
    Comparative plot: side-by-side F1-Macro for multiclass vs binary across scenarios.
    """
    plots_dir = os.path.join(output_dir, 'plots')
    os.makedirs(plots_dir, exist_ok=True)

    scenario_order = ['Real_Test', 'Scenario_A', 'Scenario_B', 'Scenario_C', 'Scenario_D']
    scenario_labels = {
        'Real_Test': 'Real Test',
        'Scenario_A': 'A: Balanced',
        'Scenario_B': 'B: Botnet Storm',
        'Scenario_C': 'C: DDoS Flood',
        'Scenario_D': 'D: Nightmare',
    }

    rows = []
    for r in results_multi:
        rows.append({'Model': r['Model'], 'Scenario': r['Scenario'],
                     'F1_Macro': r['F1_Macro'], 'Accuracy': r['Accuracy'], 'Mode': 'Multiclass'})
    for r in results_binary:
        rows.append({'Model': r['Model'], 'Scenario': r['Scenario'],
                     'F1_Macro': r['F1_Macro'], 'Accuracy': r['Accuracy'], 'Mode': 'Binary'})

    df_cmp = pd.DataFrame(rows)
    present_scenarios = [s for s in scenario_order if s in df_cmp['Scenario'].values]
    df_cmp['Scenario_Label'] = df_cmp['Scenario'].map(scenario_labels)
    scenario_label_order = [scenario_labels[s] for s in present_scenarios]

    # --- Per-model comparison across modes ---
    models = list(VICTIM_MODELS.keys())
    n_models = len(models)
    fig, axes = plt.subplots(1, n_models, figsize=(5 * n_models, 6), sharey=True)
    if n_models == 1:
        axes = [axes]

    for idx, model_name in enumerate(models):
        ax = axes[idx]
        df_model = df_cmp[df_cmp['Model'] == model_name]
        sns.barplot(
            data=df_model, x='Scenario_Label', y='F1_Macro', hue='Mode',
            order=scenario_label_order, ax=ax, edgecolor='black', linewidth=0.5,
            palette={'Multiclass': '#3498db', 'Binary': '#e74c3c'}
        )
        ax.set_title(model_name, fontweight='bold')
        ax.set_xlabel('')
        ax.set_ylabel('F1-Macro' if idx == 0 else '')
        ax.set_ylim(0, 1.05)
        ax.tick_params(axis='x', rotation=30)
        if idx > 0:
            ax.get_legend().remove()
        else:
            ax.legend(title='Mode', loc='lower left', framealpha=0.9)

        for container in ax.containers:
            ax.bar_label(container, fmt='%.2f', fontsize=6, padding=2, rotation=90)

    fig.suptitle('Multiclass vs Binary: F1-Macro Comparison Per Model', fontweight='bold', fontsize=14, y=1.02)
    plt.tight_layout()
    path = os.path.join(plots_dir, 'plot_comparison_multiclass_vs_binary.png')
    plt.savefig(path, bbox_inches='tight')
    plt.close()
    print(f"    Saved: {path}")

    # --- Heatmap: Δ F1 (Binary - Multiclass) ---
    fig, ax = plt.subplots(figsize=(10, 5))
    pivot_multi = df_cmp[df_cmp['Mode'] == 'Multiclass'].pivot_table(
        index='Model', columns='Scenario_Label', values='F1_Macro', aggfunc='first'
    )
    pivot_binary = df_cmp[df_cmp['Mode'] == 'Binary'].pivot_table(
        index='Model', columns='Scenario_Label', values='F1_Macro', aggfunc='first'
    )
    common_cols = [c for c in scenario_label_order if c in pivot_multi.columns and c in pivot_binary.columns]
    delta = pivot_binary[common_cols] - pivot_multi[common_cols]
    sns.heatmap(delta, annot=True, fmt='+.3f', cmap='RdBu', center=0,
                linewidths=0.5, ax=ax, cbar_kws={'label': 'Δ F1-Macro (Binary − Multiclass)'})
    ax.set_title('F1-Macro Difference: Binary − Multiclass', fontweight='bold')
    plt.tight_layout()
    path_delta = os.path.join(plots_dir, 'plot_delta_binary_vs_multiclass.png')
    plt.savefig(path_delta, bbox_inches='tight')
    plt.close()
    print(f"    Saved: {path_delta}")


def generate_all_plots(all_results, label_encoder, output_dir, mode='multiclass'):
    """Generate all paper-ready visualizations for a given mode."""
    mode_label = mode.upper()
    print("\n" + "=" * 70)
    print(f"[PHASE 4] GENERATING PAPER-READY VISUALIZATIONS [{mode_label}]")
    print("=" * 70)

    plots_dir = os.path.join(output_dir, 'plots')
    os.makedirs(plots_dir, exist_ok=True)

    set_paper_style()

    plot_robustness_degradation(all_results, plots_dir, mode=mode)
    plot_radar_chart(all_results, label_encoder, plots_dir, mode=mode)
    plot_confusion_matrix_botnet(all_results, label_encoder, plots_dir, mode=mode)

    print(f"\n  [OK] All {mode_label} plots saved to: {plots_dir}")


# =============================================================================
# RESULTS EXPORT & SUMMARY
# =============================================================================

def save_results_csv(all_results, output_dir, mode='multiclass'):
    """Save all numerical results to CSV for reproducibility."""
    mode_label = mode.upper()
    class_list = ALL_CLASSES if mode == 'multiclass' else BINARY_CLASSES

    rows = []
    for r in all_results:
        row = {
            'Mode': mode,
            'Model': r['Model'],
            'Scenario': r['Scenario'],
            'Scenario_Name': STRESS_SCENARIOS.get(r['Scenario'], {}).get('name', 'Real Test'),
            'Test_Samples': r['Test_Samples'],
            'Accuracy': r['Accuracy'],
            'F1_Macro': r['F1_Macro'],
            'F1_Weighted': r['F1_Weighted'],
            'Precision_Macro': r['Precision_Macro'],
            'Recall_Macro': r['Recall_Macro'],
        }

        # Add per-class F1
        for cls_name in class_list:
            if cls_name in r['Report']:
                row[f'F1_{cls_name}'] = r['Report'][cls_name]['f1-score']
                row[f'Precision_{cls_name}'] = r['Report'][cls_name]['precision']
                row[f'Recall_{cls_name}'] = r['Report'][cls_name]['recall']

        rows.append(row)

    df = pd.DataFrame(rows)
    csv_path = os.path.join(output_dir, f'stress_test_results_{mode}.csv')
    df.to_csv(csv_path, index=False)
    print(f"\n  [SAVED] {mode_label} Results CSV: {csv_path}")

    # Also save per-scenario classification reports
    for r in all_results:
        report_df = pd.DataFrame(r['Report']).transpose()
        fname = f"{r['Model']}_{r['Scenario']}_{mode}_classification_report.csv"
        report_df.to_csv(os.path.join(output_dir, fname))

    # Save confusion matrices
    for r in all_results:
        cm_labels = class_list if r['Confusion_Matrix'].shape[0] == len(class_list) else [
            f'Class_{i}' for i in range(r['Confusion_Matrix'].shape[0])
        ]
        cm_df = pd.DataFrame(
            r['Confusion_Matrix'],
            index=cm_labels,
            columns=cm_labels
        )
        fname = f"{r['Model']}_{r['Scenario']}_{mode}_confusion_matrix.csv"
        cm_df.to_csv(os.path.join(output_dir, fname))

    return df


def generate_text_summary(all_results, label_encoder, output_dir, mode='multiclass'):
    """Generate a comprehensive text summary of all results for a given mode."""
    mode_label = mode.upper()
    lines = []
    lines.append("=" * 120)
    lines.append(" " * 20 + f"NIDS ROBUSTNESS AUDIT - STRESS TESTING RESULTS [{mode_label}]")
    lines.append(" " * 20 + "Train on Real Data → Test on GAN-Generated Adversarial Traffic")
    lines.append(f" " * 40 + f"Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    lines.append("=" * 120)

    # Overview
    lines.append("\n" + "=" * 120)
    lines.append("1. EXPERIMENT OVERVIEW")
    lines.append("=" * 120)
    lines.append(f"\n  Models evaluated: {', '.join(VICTIM_MODELS.keys())}")
    lines.append(f"  Scenarios: Real Test + {len(STRESS_SCENARIOS)} adversarial scenarios")
    for sid, scfg in STRESS_SCENARIOS.items():
        total_s = sum(scfg['distribution'].values())
        lines.append(f"    {sid} ({scfg['name']}): {total_s:,} samples")
        if mode == 'multiclass':
            for cls, n in scfg['distribution'].items():
                lines.append(f"      {cls:<15}: {n:>10,} ({n/total_s*100:>5.1f}%)")
        else:
            benign_n = scfg['distribution'].get('BENIGN', 0)
            attack_n = total_s - benign_n
            lines.append(f"      {'BENIGN':<15}: {benign_n:>10,} ({benign_n/total_s*100:>5.1f}%)")
            lines.append(f"      {'ATTACK':<15}: {attack_n:>10,} ({attack_n/total_s*100:>5.1f}%)")

    # Ranking per scenario
    lines.append("\n\n" + "=" * 120)
    lines.append(f"2. MODEL RANKINGS PER SCENARIO [{mode_label}] (by F1-Macro)")
    lines.append("=" * 120)

    scenarios_seen = sorted(set(r['Scenario'] for r in all_results),
                            key=lambda x: ['Real_Test', 'Scenario_A', 'Scenario_B',
                                           'Scenario_C', 'Scenario_D'].index(x)
                            if x in ['Real_Test', 'Scenario_A', 'Scenario_B',
                                     'Scenario_C', 'Scenario_D'] else 99)

    for scenario in scenarios_seen:
        scfg = STRESS_SCENARIOS.get(scenario, {'name': 'Real Test'})
        s_name = scfg.get('name', 'Real Test')
        results_s = sorted([r for r in all_results if r['Scenario'] == scenario],
                           key=lambda x: x['F1_Macro'], reverse=True)

        lines.append(f"\n  {'─' * 100}")
        lines.append(f"  {scenario} ({s_name})")
        lines.append(f"  {'─' * 100}")
        lines.append(f"  {'Pos':<5} {'Model':<15} │ {'Accuracy':>10} {'F1-Macro':>10} "
                     f"{'F1-Weight':>10} │ {'Precision':>10} {'Recall':>10}")
        lines.append(f"  {'─' * 80}")

        for i, r in enumerate(results_s, 1):
            lines.append(f"  {i:<5} {r['Model']:<15} │ {r['Accuracy']:>10.4f} {r['F1_Macro']:>10.4f} "
                        f"{r['F1_Weighted']:>10.4f} │ {r['Precision_Macro']:>10.4f} {r['Recall_Macro']:>10.4f}")

    # Degradation analysis
    lines.append("\n\n" + "=" * 120)
    lines.append(f"3. ROBUSTNESS DEGRADATION ANALYSIS [{mode_label}] (Δ vs Real Test)")
    lines.append("=" * 120)

    real_results = {r['Model']: r for r in all_results if r['Scenario'] == 'Real_Test'}

    lines.append(f"\n  {'Model':<15} │ {'Scenario':<25} │ {'Δ Accuracy':>12} {'Δ F1-Macro':>12} "
                f"{'Δ Precision':>12} {'Δ Recall':>12}")
    lines.append(f"  {'─' * 100}")

    for r in all_results:
        if r['Scenario'] == 'Real_Test':
            continue
        baseline = real_results.get(r['Model'])
        if baseline:
            d_acc = r['Accuracy'] - baseline['Accuracy']
            d_f1 = r['F1_Macro'] - baseline['F1_Macro']
            d_prec = r['Precision_Macro'] - baseline['Precision_Macro']
            d_rec = r['Recall_Macro'] - baseline['Recall_Macro']

            s_name = STRESS_SCENARIOS.get(r['Scenario'], {}).get('name', r['Scenario'])
            lines.append(f"  {r['Model']:<15} │ {s_name:<25} │ {d_acc:>+12.4f} {d_f1:>+12.4f} "
                        f"{d_prec:>+12.4f} {d_rec:>+12.4f}")

    # Conclusions
    lines.append("\n\n" + "=" * 120)
    lines.append(f"4. KEY FINDINGS [{mode_label}]")
    lines.append("=" * 120)

    # Most robust model (smallest average degradation)
    model_degradation = {}
    for model_name in VICTIM_MODELS:
        baseline = real_results.get(model_name)
        if not baseline:
            continue
        deltas = []
        for r in all_results:
            if r['Model'] == model_name and r['Scenario'] != 'Real_Test':
                deltas.append(abs(r['F1_Macro'] - baseline['F1_Macro']))
        if deltas:
            model_degradation[model_name] = np.mean(deltas)

    if model_degradation:
        most_robust = min(model_degradation, key=model_degradation.get)
        least_robust = max(model_degradation, key=model_degradation.get)
        lines.append(f"\n  Most robust model:  {most_robust} "
                    f"(avg Δ F1-Macro = {model_degradation[most_robust]:+.4f})")
        lines.append(f"  Least robust model: {least_robust} "
                    f"(avg Δ F1-Macro = {model_degradation[least_robust]:+.4f})")

    # Worst scenario per model
    lines.append(f"\n  Worst scenario per model:")
    for model_name in VICTIM_MODELS:
        model_results = [r for r in all_results
                         if r['Model'] == model_name and r['Scenario'] != 'Real_Test']
        if model_results:
            worst = min(model_results, key=lambda x: x['F1_Macro'])
            s_name = STRESS_SCENARIOS.get(worst['Scenario'], {}).get('name', worst['Scenario'])
            lines.append(f"    {model_name:<15}: {s_name:<25} F1-Macro = {worst['F1_Macro']:.4f}")

    lines.append("\n" + "=" * 120)

    summary_text = "\n".join(lines)

    path = os.path.join(output_dir, f'STRESS_TEST_SUMMARY_{mode}.txt')
    with open(path, 'w') as f:
        f.write(summary_text)

    print(f"\n{summary_text}")
    print(f"\n  [SAVED] {mode_label} Summary: {path}")


# =============================================================================
# MAIN
# =============================================================================

def main():
    parser = argparse.ArgumentParser(
        description='NIDS Robustness Audit: Stress-Testing with GAN-Generated Adversarial Traffic',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Full experiment (all phases)
  python stress_test_nids.py

  # Specify test size
  python stress_test_nids.py --test-size 0.3

  # Custom output directory
  python stress_test_nids.py --output results_stress_test/my_run
        """
    )
    parser.add_argument('--test-size', type=float, default=0.3,
                        help='Proportion of real data for test set (default: 0.3)')
    parser.add_argument('--output', type=str, default=None,
                        help='Custom output directory')
    parser.add_argument('--skip-plots', action='store_true',
                        help='Skip plot generation')
    parser.add_argument('--gpu', type=str, default='0',
                        help='GPU to use for GAN inference (default: 0)')

    args = parser.parse_args()

    os.environ["CUDA_VISIBLE_DEVICES"] = args.gpu

    # ── Setup output directory ──
    if args.output:
        output_dir = args.output
    else:
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        output_dir = os.path.join(OUTPUT_DIR, f'stress_test_{timestamp}')
    os.makedirs(output_dir, exist_ok=True)

    print_header()
    print(f"\n  Output directory: {output_dir}")

    # ── Save experiment config ──
    config = {
        'timestamp': datetime.now().isoformat(),
        'test_size': args.test_size,
        'models_dir': MODELS_DIR,
        'random_state': RANDOM_STATE,
        'models': list(VICTIM_MODELS.keys()),
        'scenarios': {k: v['distribution'] for k, v in STRESS_SCENARIOS.items()},
        'modes': ['multiclass', 'binary'],
    }
    with open(os.path.join(output_dir, 'experiment_config.json'), 'w') as f:
        json.dump(config, f, indent=2)

    start_total = datetime.now()

    # =========================================================================
    # PHASE 0: Load and prepare real data
    # =========================================================================
    df_raw = load_real_data()
    df_features = prepare_features(df_raw, target_classes=ALL_CLASSES)

    print(f"\n  Filtered dataset: {len(df_features):,} samples")
    print(f"  Classes (multiclass): {ALL_CLASSES}")
    print(f"  Classes (binary):     {BINARY_CLASSES}")
    print(f"\n  Multiclass Distribution:")
    for cls in ALL_CLASSES:
        cnt = len(df_features[df_features['Label_Class'] == cls])
        pct = (cnt / len(df_features)) * 100
        print(f"    {cls:<15}: {cnt:>10,} ({pct:>5.1f}%)")

    # Binary distribution
    benign_cnt = len(df_features[df_features['Label_Class'] == 'BENIGN'])
    attack_cnt = len(df_features) - benign_cnt
    print(f"\n  Binary Distribution:")
    print(f"    {'BENIGN':<15}: {benign_cnt:>10,} ({benign_cnt/len(df_features)*100:>5.1f}%)")
    print(f"    {'ATTACK':<15}: {attack_cnt:>10,} ({attack_cnt/len(df_features)*100:>5.1f}%)")

    feature_cols = [c for c in df_features.columns if c != 'Label_Class']
    X = df_features[feature_cols].values

    # Multiclass label encoder
    label_encoder_multi = LabelEncoder()
    label_encoder_multi.fit(ALL_CLASSES)
    y_multi = label_encoder_multi.transform(df_features['Label_Class'])

    # Binary label encoder
    label_encoder_binary = LabelEncoder()
    label_encoder_binary.fit(BINARY_CLASSES)
    y_binary = np.where(df_features['Label_Class'].values == 'BENIGN', 0, 1)

    print(f"\n  Features: {len(feature_cols)}")
    print(f"  Multiclass encoded classes: {list(label_encoder_multi.classes_)}")
    print(f"  Binary encoded classes:     {list(label_encoder_binary.classes_)}")

    # Train/test split (same split for both modes to ensure fair comparison)
    X_train, X_test, y_train_multi, y_test_multi, y_train_binary, y_test_binary = \
        train_test_split(
            X, y_multi, y_binary,
            test_size=args.test_size,
            random_state=RANDOM_STATE,
            stratify=y_multi
        )
    print(f"\n  Train: {len(X_train):,} | Test: {len(X_test):,}")

    # Fit global scaler on training data (shared across both modes)
    scaler = MinMaxScaler()
    scaler.fit(X_train)
    X_train_clean = np.nan_to_num(X_train, nan=0, posinf=0, neginf=0)

    # =========================================================================
    # PHASE 1: Train Victim NIDS (both modes)
    # =========================================================================
    trained_models_multi = train_victim_models(X_train_clean, y_train_multi, scaler, mode='multiclass')
    trained_models_binary = train_victim_models(X_train_clean, y_train_binary, scaler, mode='binary')

    # =========================================================================
    # PHASE 2: Generate Stress Scenarios (shared — labels converted at eval time)
    # =========================================================================
    scenarios = generate_stress_scenarios()

    # =========================================================================
    # PHASE 3: Massive Evaluation — MULTICLASS
    # =========================================================================
    results_multi = run_massive_evaluation(
        trained_models_multi, scaler, label_encoder_multi,
        X_test, y_test_multi,
        scenarios, output_dir, mode='multiclass'
    )

    # =========================================================================
    # PHASE 3: Massive Evaluation — BINARY
    # =========================================================================
    results_binary = run_massive_evaluation(
        trained_models_binary, scaler, label_encoder_binary,
        X_test, y_test_binary,
        scenarios, output_dir, mode='binary'
    )

    # Save numerical results BEFORE plotting
    results_df_multi = save_results_csv(results_multi, output_dir, mode='multiclass')
    results_df_binary = save_results_csv(results_binary, output_dir, mode='binary')

    # Also save a combined CSV
    combined_df = pd.concat([results_df_multi, results_df_binary], ignore_index=True)
    combined_csv_path = os.path.join(output_dir, 'stress_test_results_combined.csv')
    combined_df.to_csv(combined_csv_path, index=False)
    print(f"\n  [SAVED] Combined Results CSV: {combined_csv_path}")

    # =========================================================================
    # PHASE 4: Visualizations (both modes)
    # =========================================================================
    if not args.skip_plots:
        generate_all_plots(results_multi, label_encoder_multi, output_dir, mode='multiclass')
        generate_all_plots(results_binary, label_encoder_binary, output_dir, mode='binary')

        # ── Comparative plot: Multiclass vs Binary ──
        print("\n  Generating Comparative Plot: Multiclass vs Binary...")
        set_paper_style()
        _plot_multiclass_vs_binary(results_multi, results_binary, output_dir)

    # =========================================================================
    # Summary (both modes)
    # =========================================================================
    generate_text_summary(results_multi, label_encoder_multi, output_dir, mode='multiclass')
    generate_text_summary(results_binary, label_encoder_binary, output_dir, mode='binary')

    elapsed_total = datetime.now() - start_total
    print(f"\n{'=' * 100}")
    print(f"  EXPERIMENT COMPLETED IN {elapsed_total}")
    print(f"  Results: {output_dir}")
    print(f"  CSV (multiclass): {os.path.join(output_dir, 'stress_test_results_multiclass.csv')}")
    print(f"  CSV (binary):     {os.path.join(output_dir, 'stress_test_results_binary.csv')}")
    print(f"  CSV (combined):   {combined_csv_path}")
    print(f"  Plots:            {os.path.join(output_dir, 'plots/')}")
    print(f"  Summary (multi):  {os.path.join(output_dir, 'STRESS_TEST_SUMMARY_multiclass.txt')}")
    print(f"  Summary (binary): {os.path.join(output_dir, 'STRESS_TEST_SUMMARY_binary.txt')}")
    print(f"{'=' * 100}")


if __name__ == "__main__":
    main()
