#!/usr/bin/env python3
"""
NIDS Robustness Audit: Stress-Testing with GAN-Generated Adversarial Traffic

Trains NIDS classifiers on real data and evaluates robustness against
extreme adversarial scenarios generated by WGAN-GP models.
"""

import os 
import sys 
import json 
import pickle 
import argparse 
import warnings 
import math 
import numpy as np 
import pandas as pd 
import polars as pl 
from datetime import datetime 
from collections import Counter 

from sklearn .preprocessing import MinMaxScaler ,LabelEncoder 
from sklearn .model_selection import train_test_split 
from sklearn .metrics import (
classification_report ,confusion_matrix ,
accuracy_score ,f1_score ,precision_score ,recall_score 
)
from sklearn .linear_model import LogisticRegression 
from sklearn .ensemble import RandomForestClassifier 
from sklearn .neighbors import KNeighborsClassifier 
from lightgbm import LGBMClassifier 
from xgboost import XGBClassifier 

import matplotlib 
matplotlib .use ('Agg')
import matplotlib .ticker as mticker 
from matplotlib .patches import Patch 
import matplotlib .pyplot as plt 
import seaborn as sns 

import tensorflow as tf 
from tensorflow .keras .models import load_model 

warnings .filterwarnings ('ignore')
os .environ ['TF_CPP_MIN_LOG_LEVEL']='2'

from dotenv import load_dotenv 


load_dotenv ()


RANDOM_STATE =42 
LATENT_DIM =int (os .getenv ('LATENT_DIM',100 ))

DATASETS ={
'cicids2017':{
'REAL_DATA_PATH':'./data/CIC-IDS2017.csv',
'MODELS_DIR':'./outputs/models',
'OUTPUT_DIR':'./outputs/results',
'LABEL_COL':'Label',
'BENIGN_LABEL':'BENIGN',
'ALL_CLASSES':['BENIGN','Bot','Brute Force','DDoS','DoS','Port Scan','Web Attack'],
'BINARY_CLASSES':['BENIGN','ATTACK'],
'CLASS_TO_FOLDER':{
'BENIGN':'benign','Bot':'bot','Brute Force':'brute_force',
'DDoS':'ddos','DoS':'dos','Port Scan':'port_scan','Web Attack':'web_attack',
},
'FEATURES_BASE':[
'Source Port','Destination Port','Protocol',
'Total Fwd Packets','Total Backward Packets',
'Total Length of Fwd Packets','Total Length of Bwd Packets',
'Flow Duration','Flow IAT Mean','Flow IAT Std',
'Fwd IAT Mean','Bwd IAT Mean',
'Fwd Packet Length Mean','Bwd Packet Length Mean',
'Packet Length Std','Max Packet Length',
'SYN Flag Count','ACK Flag Count','FIN Flag Count',
'RST Flag Count','PSH Flag Count'
],
'IP_COLS':('Source IP','Destination IP'),
'FEATURE_NAMES_IP':[
'Src_IP_1','Src_IP_2','Src_IP_3','Src_IP_4',
'Dst_IP_1','Dst_IP_2','Dst_IP_3','Dst_IP_4'
],
'LOG_COLUMNS':[
'Total Fwd Packets','Total Backward Packets',
'Total Length of Fwd Packets','Total Length of Bwd Packets',
'Flow Duration','Flow IAT Mean','Flow IAT Std',
'Fwd IAT Mean','Bwd IAT Mean',
'Fwd Packet Length Mean','Bwd Packet Length Mean',
'Packet Length Std','Max Packet Length'
],
'SCENARIOS':{
'Scenario_A':{'name':'Baseline','description':'Balanced benchmark','distribution':{'BENIGN':10000 ,'Bot':2000 ,'Brute Force':2000 ,'DDoS':2000 ,'DoS':2000 ,'Port Scan':2000 ,'Web Attack':2000 }},
'Scenario_B':{'name':'Botnet Storm','description':'Massive botnet attack','distribution':{'BENIGN':5000 ,'Bot':50000 }},
'Scenario_C':{'name':'DDoS Flood','description':'Volumetric saturation','distribution':{'BENIGN':5000 ,'DDoS':40000 ,'DoS':40000 }},
'Scenario_D':{'name':'Inverse Imbalance','description':'Nightmare','distribution':{'BENIGN':1000 ,'Bot':10000 ,'Brute Force':10000 ,'DDoS':10000 ,'DoS':10000 ,'Port Scan':10000 ,'Web Attack':10000 }},
}
},
'unsw-nb15':{
'REAL_DATA_PATH':os .getenv ('DATA_UNSW_PATH','./data/UNSW-NB15.csv'),
'MODELS_DIR':os .getenv ('OUTPUT_MODELS_DIR','./outputs/models'),
'OUTPUT_DIR':os .getenv ('OUTPUT_RESULTS_DIR','./outputs/results'),
'LABEL_COL':'Label',
'BENIGN_LABEL':'Benign',
'ALL_CLASSES':['Benign','Exploits','Fuzzers','Reconnaissance','Generic','DoS','Shellcode'],
'BINARY_CLASSES':['Benign','ATTACK'],
'CLASS_TO_FOLDER':{
'Benign':'benign','Exploits':'exploits','Fuzzers':'fuzzers',
'Reconnaissance':'reconnaissance','Generic':'generic','DoS':'dos','Shellcode':'shellcode'
},
'FEATURES_BASE':[
'Src Port','Dst Port','Protocol',
'Total Fwd Packet','Total Bwd packets',
'Total Length of Fwd Packet','Total Length of Bwd Packet',
'Flow Duration','Flow IAT Mean','Flow IAT Std',
'Fwd IAT Mean','Bwd IAT Mean',
'Fwd Packet Length Mean','Bwd Packet Length Mean',
'Packet Length Std','Packet Length Max',
'SYN Flag Count','ACK Flag Count','FIN Flag Count',
'RST Flag Count','PSH Flag Count'
],
'IP_COLS':('Src IP','Dst IP'),
'FEATURE_NAMES_IP':[
'Src_IP_1','Src_IP_2','Src_IP_3','Src_IP_4',
'Dst_IP_1','Dst_IP_2','Dst_IP_3','Dst_IP_4'
],
'LOG_COLUMNS':[
'Total Fwd Packet','Total Bwd packets',
'Total Length of Fwd Packet','Total Length of Bwd Packet',
'Flow Duration','Flow IAT Mean','Flow IAT Std',
'Fwd IAT Mean','Bwd IAT Mean',
'Fwd Packet Length Mean','Bwd Packet Length Mean',
'Packet Length Std','Packet Length Max'
],
'SCENARIOS':{
'Scenario_A':{'name':'Baseline','description':'Balanced benchmark','distribution':{'Benign':10000 ,'Exploits':2500 ,'Fuzzers':2500 ,'Reconnaissance':2500 ,'Generic':2500 ,'DoS':2500 ,'Shellcode':2500 }},
'Scenario_B':{'name':'Shellcode Surge','description':'Massive shellcode attack','distribution':{'Benign':5000 ,'Shellcode':50000 }},
'Scenario_C':{'name':'DoS/Generic Flood','description':'Volumetric saturation','distribution':{'Benign':5000 ,'DoS':40000 ,'Generic':40000 }},
'Scenario_D':{'name':'Inverse Imbalance','description':'Nightmare','distribution':{'Benign':1000 ,'Exploits':10000 ,'Fuzzers':10000 ,'Reconnaissance':10000 ,'Generic':10000 ,'DoS':10000 ,'Shellcode':10000 }},
}
},
'edgeiiot':{
'REAL_DATA_PATH':os .getenv ('DATA_EDGEIIOT_PATH','./data/Edge-IIoT.csv'),
'MODELS_DIR':os .getenv ('OUTPUT_MODELS_DIR','./outputs/models'),
'OUTPUT_DIR':os .getenv ('OUTPUT_RESULTS_DIR','./outputs/results'),
'LABEL_COL':'Attack_type',
'BENIGN_LABEL':'Normal',
'ALL_CLASSES':['Normal','DDoS_UDP','DDoS_ICMP','SQL_injection','Password','Vulnerability_scanner','DDoS_TCP','DDoS_HTTP','Uploading','Backdoor','Port_Scanning','XSS','Ransomware','MITM','Fingerprinting'],
'BINARY_CLASSES':['Normal','ATTACK'],
'CLASS_TO_FOLDER':{
'Normal':'normal','DDoS_UDP':'ddos_udp','DDoS_ICMP':'ddos_icmp','SQL_injection':'sql_injection',
'Password':'password','Vulnerability_scanner':'vulnerability_scanner','DDoS_TCP':'ddos_tcp',
'DDoS_HTTP':'ddos_http','Uploading':'uploading','Backdoor':'backdoor','Port_Scanning':'port_scanning',
'XSS':'xss','Ransomware':'ransomware','MITM':'mitm','Fingerprinting':'fingerprinting'
},
'FEATURES_BASE':[
'arp.opcode','arp.hw.size','icmp.checksum','icmp.seq_le','icmp.transmit_timestamp','icmp.unused',
'http.file_data','http.content_length','http.request.uri.query','http.request.method','http.referer','http.request.full_uri',
'http.request.version','http.response','http.tls_port','tcp.ack','tcp.ack_raw','tcp.checksum',
'tcp.connection.fin','tcp.connection.rst','tcp.connection.syn','tcp.connection.synack','tcp.dstport','tcp.flags','tcp.flags.ack',
'tcp.len','tcp.seq','tcp.srcport','udp.port','udp.stream','udp.time_delta',
'dns.qry.name','dns.qry.name.len','dns.qry.qu','dns.qry.type','dns.retransmission','dns.retransmit_request','dns.retransmit_request_in',
'mqtt.conflag.cleansess','mqtt.conflags','mqtt.hdrflags','mqtt.len','mqtt.msg_decoded_as','mqtt.msgtype',
'mqtt.proto_len','mqtt.topic_len','mqtt.ver','mbtcp.len','mbtcp.trans_id','mbtcp.unit_id'
],
'IP_COLS':('ip.src_host','ip.dst_host'),
'FEATURE_NAMES_IP':[
'Src_IP_1','Src_IP_2','Src_IP_3','Src_IP_4',
'Dst_IP_1','Dst_IP_2','Dst_IP_3','Dst_IP_4'
],
'LOG_COLUMNS':[
'tcp.ack_raw','tcp.checksum','tcp.seq','tcp.srcport','tcp.dstport',
'tcp.len','udp.port','http.content_length','http.file_data','icmp.checksum'
],
'SCENARIOS':{
'Scenario_A':{
'name':'Baseline',
'description':'45% normal traffic, remaining classes balanced',
'distribution':{
'Normal':9000 ,
**{
c :(786 if i <10 else 785 )
for i ,c in enumerate ([
'DDoS_UDP','DDoS_ICMP','SQL_injection','Password',
'Vulnerability_scanner','DDoS_TCP','DDoS_HTTP','Uploading',
'Backdoor','Port_Scanning','XSS','Ransomware','MITM','Fingerprinting'
])
}
}
},
'Scenario_B':{
'name':'Ransomware Outbreak',
'description':'90% ransomware traffic',
'distribution':{'Normal':5500 ,'Ransomware':49500 }
},
'Scenario_C':{
'name':'Multi-Vector DDoS Flood',
'description':'Combined UDP/ICMP/TCP/HTTP volumetric saturation',
'distribution':{
'Normal':5900 ,
'DDoS_TCP':23500 ,
'DDoS_UDP':23500 ,
'DDoS_ICMP':23500 ,
'DDoS_HTTP':23500 
}
},
'Scenario_D':{'name':'Inverse Imbalance','description':'Nightmare','distribution':{'Normal':1000 ,'DDoS_UDP':5000 ,'DDoS_ICMP':5000 ,'SQL_injection':5000 ,'Password':5000 ,'Vulnerability_scanner':5000 ,'DDoS_TCP':5000 ,'DDoS_HTTP':5000 ,'Uploading':5000 ,'Backdoor':5000 ,'Port_Scanning':5000 ,'XSS':5000 ,'Ransomware':5000 ,'MITM':5000 ,'Fingerprinting':5000 }},
}
}
}

def set_dataset (ds_name ):
    global CFG ,REAL_DATA_PATH ,MODELS_DIR ,OUTPUT_DIR ,LABEL_COL ,BENIGN_LABEL ,ALL_CLASSES ,BINARY_CLASSES 
    global CLASS_TO_FOLDER ,FEATURES_BASE ,IP_COLS ,FEATURE_NAMES_IP ,FEATURE_NAMES ,LOG_COLUMNS ,STRESS_SCENARIOS 
    CFG =DATASETS [ds_name ]
    REAL_DATA_PATH =CFG ['REAL_DATA_PATH']
    MODELS_DIR =CFG ['MODELS_DIR']
    OUTPUT_DIR =CFG ['OUTPUT_DIR']
    LABEL_COL =CFG ['LABEL_COL']
    BENIGN_LABEL =CFG ['BENIGN_LABEL']
    ALL_CLASSES =CFG ['ALL_CLASSES']
    BINARY_CLASSES =CFG ['BINARY_CLASSES']
    CLASS_TO_FOLDER =CFG ['CLASS_TO_FOLDER']
    FEATURES_BASE =CFG ['FEATURES_BASE']
    IP_COLS =CFG ['IP_COLS']
    FEATURE_NAMES_IP =CFG ['FEATURE_NAMES_IP']
    FEATURE_NAMES =FEATURES_BASE +FEATURE_NAMES_IP 
    LOG_COLUMNS =CFG ['LOG_COLUMNS']
    STRESS_SCENARIOS =CFG ['SCENARIOS']

set_dataset ('cicids2017')




def build_victim_models (fast =False ):
    """Return victim model factories. In fast mode, use lighter configs."""
    if fast :
        return {
        'RandomForest':lambda :RandomForestClassifier (
        n_estimators =60 ,max_depth =12 ,n_jobs =-1 ,random_state =RANDOM_STATE 
        ),
        'KNeighbors':lambda :KNeighborsClassifier (
        n_neighbors =3 ,n_jobs =-1 
        ),
        'LGBM':lambda :LGBMClassifier (
        n_estimators =90 ,learning_rate =0.10 ,num_leaves =31 ,
        subsample =0.9 ,colsample_bytree =0.9 ,
        random_state =RANDOM_STATE ,n_jobs =-1 ,verbosity =-1 
        ),
        'LR':lambda :LogisticRegression (
        max_iter =1000 ,random_state =RANDOM_STATE ,n_jobs =-1 
        ),
        }

    return {
    'RandomForest':lambda :RandomForestClassifier (
    n_estimators =120 ,max_depth =16 ,n_jobs =-1 ,random_state =RANDOM_STATE 
    ),
    'KNeighbors':lambda :KNeighborsClassifier (
    n_neighbors =5 ,n_jobs =-1 
    ),
    'LGBM':lambda :LGBMClassifier (
    n_estimators =180 ,learning_rate =0.08 ,num_leaves =31 ,
    subsample =0.9 ,colsample_bytree =0.9 ,
    random_state =RANDOM_STATE ,n_jobs =-1 ,verbosity =-1 
    ),
    'LR':lambda :LogisticRegression (
    max_iter =1000 ,random_state =RANDOM_STATE ,n_jobs =-1 
    ),
    }


VICTIM_MODELS =build_victim_models (fast =False )






def convert_to_binary_labels (y_multiclass ,label_encoder_multi ):
    """Convert multiclass encoded labels to binary (0=BENIGN, 1=ATTACK)."""
    class_names =label_encoder_multi .inverse_transform (y_multiclass )
    y_binary =np .where (class_names ==BENIGN_LABEL ,0 ,1 )
    return y_binary 


def convert_scenario_to_binary (df_scenario ):
    """Convert scenario DataFrame labels to binary."""
    df =df_scenario .copy ()
    df ['Label_Class']=df ['Label_Class'].apply (lambda x :BENIGN_LABEL if x ==BENIGN_LABEL else 'ATTACK')
    return df 


def print_header ():
    print ("="*100 )
    print ("  NIDS ROBUSTNESS AUDIT - STRESS TESTING WITH GAN-GENERATED TRAFFIC")
    print ("  Train on Real Data -> Test on Adversarial Scenarios")
    print ("  Mode: MULTICLASS")
    print ("="*100 )
    print (f"  Date: {datetime .now ().strftime ('%Y-%m-%d %H:%M:%S')}")
    print (f"  Random State: {RANDOM_STATE }")
    print ("="*100 )


def load_real_data ():
    """Load the CIC-IDS2017 dataset."""
    print ("\n"+"="*70 )
    print ("[PHASE 0] LOADING REAL DATA")
    print ("="*70 )

    file_size =os .path .getsize (REAL_DATA_PATH )
    print (f"  File: {REAL_DATA_PATH }")
    print (f"  Size: {file_size /(1024 *1024 ):.2f} MB")

    start_time =datetime .now ()
    try :
        df_pl =pl .read_csv (REAL_DATA_PATH ,ignore_errors =True ,infer_schema_length =10000 )
        df =df_pl .to_pandas ()
    except Exception :
        print ("  Polars read_csv failed, falling back to pandas...")
        df =pd .read_csv (REAL_DATA_PATH ,low_memory =False )

    df .columns =df .columns .str .strip ()
    print (f"  Loaded in {datetime .now ()-start_time }")
    print (f"  Total records: {len (df ):,}")

    return df 


def prepare_features (df :pd .DataFrame ,target_classes =None )->pd .DataFrame :
    """Prepare feature matrix from raw CIC-IDS2017 data."""
    df =df .copy ()

    label_col =LABEL_COL 
    df ['Label_Class']=df [label_col ]

    if target_classes is not None :
        df =df [df ['Label_Class'].isin (target_classes )].copy ()

    features_df =df [FEATURES_BASE ].copy ()


    if IP_COLS [0 ]in df .columns :
        octets =df [IP_COLS [0 ]].astype (str ).str .split ('.',expand =True )
        for i in range (4 ):
            features_df [f'Src_IP_{i +1 }']=pd .to_numeric (octets .get (i ,0 ),errors ='coerce').fillna (0 ).astype (int )
    else :
        for i in range (4 ):
            features_df [f'Src_IP_{i +1 }']=0 

    if IP_COLS [1 ]in df .columns :
        octets =df [IP_COLS [1 ]].astype (str ).str .split ('.',expand =True )
        for i in range (4 ):
            features_df [f'Dst_IP_{i +1 }']=pd .to_numeric (octets .get (i ,0 ),errors ='coerce').fillna (0 ).astype (int )
    else :
        for i in range (4 ):
            features_df [f'Dst_IP_{i +1 }']=0 


    features_df ['Label_Class']=df ['Label_Class'].values 

    features_df .replace ([np .inf ,-np .inf ],np .nan ,inplace =True )
    features_df .fillna (0 ,inplace =True )

    return features_df 






def train_victim_models (X_train ,y_train ,scaler ,mode ='multiclass'):
    """Train all victim NIDS models on real (clean) data."""
    mode_label =mode .upper ()
    print ("\n"+"="*70 )
    print (f"[PHASE 1] TRAINING VICTIM NIDS - {mode_label } (Gold Standard)")
    print ("="*70 )
    n_classes =len (np .unique (y_train ))
    print (f"  Mode: {mode_label } ({n_classes } classes)")
    print (f"  Training samples: {len (X_train ):,}")
    print (f"  Models: {', '.join (VICTIM_MODELS .keys ())}")

    X_train_scaled =scaler .transform (X_train )
    X_train_scaled =np .nan_to_num (X_train_scaled ,nan =0 ,posinf =0 ,neginf =0 )

    trained_models ={}
    for name ,model_fn in VICTIM_MODELS .items ():
        print (f"\n  Training {name } [{mode_label }]...",end =" ",flush =True )
        model =model_fn ()
        start_time =datetime .now ()
        model .fit (X_train_scaled ,y_train )
        elapsed =datetime .now ()-start_time 
        print (f"Done ({elapsed })")
        trained_models [name ]=model 

    print (f"\n  [OK] {len (trained_models )} {mode_label } models trained successfully.")
    return trained_models 






def get_available_generators ():
    """Discover available WGAN-GP v2 generators."""
    available ={}
    for class_name ,folder in CLASS_TO_FOLDER .items ():
        model_path =os .path .join (MODELS_DIR ,folder ,f'generator_{folder }.h5')
        if os .path .exists (model_path ):
            available [class_name ]={
            'folder':folder ,
            'model_path':model_path ,
            'source_dir':MODELS_DIR ,
            }
    return available 


def load_scaler_for_class (class_name ,source_dir ):
    """Load or recreate the MinMaxScaler for a given class."""
    folder =CLASS_TO_FOLDER [class_name ]

    search_dirs =[source_dir ]if source_dir else [MODELS_DIR ]

    for sd in search_dirs :
        if sd is None :
            continue 
        scaler_path =os .path .join (sd ,folder ,'scaler.pkl')
        if os .path .exists (scaler_path ):
            with open (scaler_path ,'rb')as f :
                return pickle .load (f )


    print (f"    Recreating scaler for {class_name } from original data...")

    df_pl =pl .read_csv (REAL_DATA_PATH ,low_memory =False )
    df =df_pl .to_pandas ()
    df .columns =df .columns .str .strip ()
    df_cls =df [df [LABEL_COL ]==class_name ].copy ()

    features =df_cls [FEATURES_BASE ].copy ()

    if IP_COLS [0 ]in df_cls .columns :
        octets =df_cls [IP_COLS [0 ]].astype (str ).str .split ('.',expand =True )
        for i in range (4 ):
            features [f'Src_IP_{i +1 }']=pd .to_numeric (octets .get (i ,0 ),errors ='coerce').fillna (0 ).astype (int )
    else :
        for i in range (4 ):
            features [f'Src_IP_{i +1 }']=0 
    if IP_COLS [1 ]in df_cls .columns :
        octets =df_cls [IP_COLS [1 ]].astype (str ).str .split ('.',expand =True )
        for i in range (4 ):
            features [f'Dst_IP_{i +1 }']=pd .to_numeric (octets .get (i ,0 ),errors ='coerce').fillna (0 ).astype (int )
    else :
        for i in range (4 ):
            features [f'Dst_IP_{i +1 }']=0 



    for col in LOG_COLUMNS :
        features [col ]=np .log1p (features [col ].clip (lower =0 ))
        features [col ]=features [col ].clip (lower =-20 ,upper =20 )

    features .replace ([np .inf ,-np .inf ],np .nan ,inplace =True )
    features .fillna (0 ,inplace =True )

    scaler =MinMaxScaler (feature_range =(-1 ,1 ))
    scaler .fit (features [FEATURE_NAMES ])

    scaler_path =os .path .join (source_dir or MODELS_DIR ,folder ,'scaler.pkl')
    try :
        with open (scaler_path ,'wb')as f :
            pickle .dump (scaler ,f )
    except Exception :
        pass 

    return scaler 


def generate_gan_samples (generator ,n_samples ,latent_dim =LATENT_DIM ,batch_size =1024 ):
    """Generate synthetic samples from a WGAN-GP generator."""
    all_samples =[]
    remaining =n_samples 

    while remaining >0 :
        current_batch =min (batch_size ,remaining )
        noise =np .random .normal (0 ,1 ,(current_batch ,latent_dim ))
        samples =generator .predict (noise ,verbose =0 )
        all_samples .append (samples )
        remaining -=current_batch 

    return np .vstack (all_samples )


def reconstruct_features (X_synthetic ,scaler ):
    """Inverse-transform GAN output back to original feature space."""
    X_inv =scaler .inverse_transform (X_synthetic )
    df_rec =pd .DataFrame (X_inv ,columns =FEATURE_NAMES )

    for col in LOG_COLUMNS :
        df_rec [col ]=np .expm1 (df_rec [col ])

    for col in df_rec .columns :
        if col .startswith ('Src_IP_')or col .startswith ('Dst_IP_'):
            df_rec [col ]=df_rec [col ].round ().clip (0 ,255 ).astype (int )

    if 'Source Port'in df_rec .columns :df_rec ['Source Port']=df_rec ['Source Port'].round ().clip (1 ,65535 ).astype (int )
    if 'Destination Port'in df_rec .columns :df_rec ['Destination Port']=df_rec ['Destination Port'].round ().clip (1 ,65535 ).astype (int )
    if 'Protocol'in df_rec .columns :df_rec ['Protocol']=df_rec ['Protocol'].round ().clip (1 ,255 ).astype (int )

    for col in LOG_COLUMNS +['SYN Flag Count','ACK Flag Count',
    'FIN Flag Count','RST Flag Count','PSH Flag Count']:
        if col in df_rec .columns :
            df_rec [col ]=df_rec [col ].clip (lower =0 )

    integer_columns =['Total Fwd Packets','Total Backward Packets',
    'Total Fwd Packet','Total Bwd packets',
    'SYN Flag Count','ACK Flag Count',
    'FIN Flag Count','RST Flag Count','PSH Flag Count']
    for col in integer_columns :
        if col in df_rec .columns :
            df_rec [col ]=df_rec [col ].round ().astype (int )

    return df_rec 


def generate_stress_scenarios ():
    """Generate all stress-test datasets using WGAN-GP v2 models."""
    print ("\n"+"="*70 )
    print ("[PHASE 2] GENERATING STRESS-TEST SCENARIOS VIA GAN")
    print ("="*70 )

    available =get_available_generators ()
    print (f"\n  Available generators: {len (available )}")
    for cls ,info in available .items ():
        print (f"    {cls :<15} -> {info ['model_path']}")

    scenarios ={}

    for scenario_id ,scenario_cfg in STRESS_SCENARIOS .items ():
        print (f"\n  {'─'*60 }")
        print (f"  Generating {scenario_id }: {scenario_cfg ['name']}")
        print (f"  {scenario_cfg ['description']}")
        print (f"  {'─'*60 }")

        distribution =scenario_cfg ['distribution']
        parts =[]

        for class_name ,n_samples in distribution .items ():
            if n_samples <=0 :
                continue 

            if class_name not in available :
                print (f"    [WARN] No generator for '{class_name }', skipping.")
                continue 

            print (f"    {class_name }: generating {n_samples :,} samples...",end =" ",flush =True )

            gen_info =available [class_name ]
            generator =load_model (gen_info ['model_path'],compile =False )
            gan_scaler =load_scaler_for_class (class_name ,gen_info ['source_dir'])

            X_synth =generate_gan_samples (generator ,n_samples )
            df_synth =reconstruct_features (X_synth ,gan_scaler )
            df_synth ['Label_Class']=class_name 

            parts .append (df_synth )
            print (f"OK ({len (df_synth ):,})")

            del generator 
            tf .keras .backend .clear_session ()

        if parts :
            df_scenario =pd .concat (parts ,ignore_index =True )
            df_scenario =df_scenario .sample (frac =1 ,random_state =RANDOM_STATE ).reset_index (drop =True )
            scenarios [scenario_id ]=df_scenario 

            total =len (df_scenario )
            print (f"\n    Total {scenario_id }: {total :,} samples")
            for cls in distribution :
                if cls in df_scenario ['Label_Class'].values :
                    cnt =len (df_scenario [df_scenario ['Label_Class']==cls ])
                    print (f"      {cls :<15}: {cnt :>10,} ({cnt /total *100 :>5.1f}%)")

    print (f"\n  [OK] {len (scenarios )} scenarios generated.")
    return scenarios 






def evaluate_model_on_scenario (model ,model_name ,X_test ,y_test ,
label_encoder ,scenario_name ,mode ='multiclass'):
    """Evaluate a single model on a single scenario."""
    y_pred =model .predict (X_test )



    all_labels =list (range (len (label_encoder .classes_ )))

    accuracy =accuracy_score (y_test ,y_pred )
    f1_macro =f1_score (y_test ,y_pred ,average ='macro',zero_division =0 ,labels =all_labels )
    f1_weighted =f1_score (y_test ,y_pred ,average ='weighted',zero_division =0 ,labels =all_labels )
    precision_macro =precision_score (y_test ,y_pred ,average ='macro',zero_division =0 ,labels =all_labels )
    recall_macro =recall_score (y_test ,y_pred ,average ='macro',zero_division =0 ,labels =all_labels )

    report =classification_report (
    y_test ,y_pred ,
    labels =all_labels ,
    target_names =label_encoder .classes_ ,
    output_dict =True ,
    zero_division =0 
    )

    cm =confusion_matrix (y_test ,y_pred ,labels =all_labels )

    return {
    'Model':model_name ,
    'Scenario':scenario_name ,
    'Mode':mode ,
    'Accuracy':accuracy ,
    'F1_Macro':f1_macro ,
    'F1_Weighted':f1_weighted ,
    'Precision_Macro':precision_macro ,
    'Recall_Macro':recall_macro ,
    'Test_Samples':len (y_test ),
    'Report':report ,
    'Confusion_Matrix':cm ,
    }


def run_massive_evaluation (trained_models ,scaler ,label_encoder ,
X_test_real ,y_test_real ,
scenarios ,output_dir ,mode ='multiclass'):
    """Evaluate every model on every scenario (including real baseline)."""
    mode_label =mode .upper ()
    print ("\n"+"="*70 )
    print (f"[PHASE 3] MASSIVE EVALUATION - {mode_label }")
    print ("="*70 )

    all_results =[]


    print (f"\n  {'━'*60 }")
    print (f"  [{mode_label }] Evaluating on REAL TEST SET (baseline)")
    print (f"  {'━'*60 }")

    X_real_scaled =scaler .transform (X_test_real )
    X_real_scaled =np .nan_to_num (X_real_scaled ,nan =0 ,posinf =0 ,neginf =0 )

    for model_name ,model in trained_models .items ():
        result =evaluate_model_on_scenario (
        model ,model_name ,X_real_scaled ,y_test_real ,
        label_encoder ,'Real_Test',mode =mode 
        )
        all_results .append (result )
        print (f"    {model_name :<15} Acc={result ['Accuracy']:.4f}  "
        f"F1-M={result ['F1_Macro']:.4f}  F1-W={result ['F1_Weighted']:.4f}")


    for scenario_id ,df_scenario in scenarios .items ():
        scenario_name =STRESS_SCENARIOS [scenario_id ]['name']
        print (f"\n  {'━'*60 }")
        print (f"  [{mode_label }] Evaluating on {scenario_id }: {scenario_name }")
        print (f"  Samples: {len (df_scenario ):,}")
        print (f"  {'━'*60 }")


        if mode =='binary':
            df_eval =convert_scenario_to_binary (df_scenario )
        else :
            df_eval =df_scenario .copy ()


        feature_cols =[c for c in FEATURE_NAMES if c in df_eval .columns ]
        X_scenario =df_eval [feature_cols ].values 
        X_scenario =np .nan_to_num (X_scenario ,nan =0 ,posinf =0 ,neginf =0 )


        scenario_classes =df_eval ['Label_Class'].unique ()
        known_classes =set (label_encoder .classes_ )
        unknown =set (scenario_classes )-known_classes 
        if unknown :
            print (f"    [WARN] Unknown classes in scenario: {unknown }. Skipping those samples.")
            df_eval =df_eval [df_eval ['Label_Class'].isin (known_classes )].copy ()
            X_scenario =df_eval [feature_cols ].values 
            X_scenario =np .nan_to_num (X_scenario ,nan =0 ,posinf =0 ,neginf =0 )

        y_scenario =label_encoder .transform (df_eval ['Label_Class'])

        X_scenario_scaled =scaler .transform (X_scenario )
        X_scenario_scaled =np .nan_to_num (X_scenario_scaled ,nan =0 ,posinf =0 ,neginf =0 )

        for model_name ,model in trained_models .items ():
            result =evaluate_model_on_scenario (
            model ,model_name ,X_scenario_scaled ,y_scenario ,
            label_encoder ,scenario_id ,mode =mode 
            )
            all_results .append (result )
            print (f"    {model_name :<15} Acc={result ['Accuracy']:.4f}  "
            f"F1-M={result ['F1_Macro']:.4f}  F1-W={result ['F1_Weighted']:.4f}")

    return all_results 






def set_paper_style ():
    """Configure matplotlib/seaborn for publication-quality figures."""
    plt .rcParams .update ({
    'figure.dpi':150 ,
    'savefig.dpi':300 ,
    'font.size':11 ,
    'axes.titlesize':13 ,
    'axes.labelsize':12 ,
    'xtick.labelsize':10 ,
    'ytick.labelsize':10 ,
    'legend.fontsize':10 ,
    'figure.figsize':(10 ,6 ),
    'axes.grid':True ,
    'grid.alpha':0.3 ,
    'axes.spines.top':False ,
    'axes.spines.right':False ,
    })
    sns .set_theme (style ='whitegrid',palette ='muted',font_scale =1.1 )


def build_scenario_labels (multiline =False ,include_name =False ):
    """Build scenario labels dynamically from current dataset configuration."""
    import textwrap 
    labels ={'Real_Test':'Real Test'}
    for scenario_id in ['Scenario_A','Scenario_B','Scenario_C','Scenario_D']:
        if scenario_id not in STRESS_SCENARIOS :
            continue 
        scenario_name =STRESS_SCENARIOS [scenario_id ]['name']
        scenario_suffix =scenario_id .split ('_')[-1 ]

        base_label =f"Sc. {scenario_suffix }"if multiline else f"{scenario_suffix }"

        if include_name :
            wrapped_name =textwrap .fill (scenario_name ,width =15 )
            labels [scenario_id ]=f"{base_label }\n{wrapped_name }"if multiline else f"{base_label } - {scenario_name }"
        else :
            labels [scenario_id ]=base_label 

    return labels 


def plot_robustness_degradation (all_results ,output_dir ,mode ='multiclass'):
    """
    Graph 1: Grouped bar chart showing F1-Macro degradation per model across scenarios.
    """
    mode_label =mode .upper ()
    print (f"\n  Generating Plot 1: Robustness Degradation [{mode_label }]...")

    df_res =pd .DataFrame ([{
    'Model':r ['Model'],
    'Scenario':r ['Scenario'],
    'F1_Macro':r ['F1_Macro'],
    'Precision_Macro':r ['Precision_Macro'],
    'Recall_Macro':r ['Recall_Macro'],
    'Accuracy':r ['Accuracy'],
    }for r in all_results ])


    scenario_order =['Real_Test','Scenario_A','Scenario_B','Scenario_C','Scenario_D']
    scenario_labels =build_scenario_labels (multiline =False )

    present_scenarios =[s for s in scenario_order if s in df_res ['Scenario'].values ]
    df_plot =df_res [df_res ['Scenario'].isin (present_scenarios )].copy ()
    df_plot ['Scenario_Label']=df_plot ['Scenario'].map (scenario_labels )


    fig ,axes =plt .subplots (1 ,2 ,figsize =(18 ,7 ))

    scenario_label_order =[scenario_labels [s ]for s in present_scenarios ]

    ax =axes [0 ]
    sns .barplot (
    data =df_plot ,x ='Scenario_Label',y ='F1_Macro',hue ='Model',
    order =scenario_label_order ,ax =ax ,edgecolor ='black',linewidth =0.5 
    )
    ax .set_title (f'F1-Score (Macro) Degradation [{mode_label }]',fontweight ='bold')
    ax .set_xlabel ('Test Scenario')
    ax .set_ylabel ('F1-Score (Macro)')
    ax .set_ylim (0 ,1.05 )
    ax .legend (title ='Model',loc ='lower left',framealpha =0.9 )


    for container in ax .containers :
        ax .bar_label (container ,fmt ='%.2f',fontsize =7 ,padding =2 ,rotation =90 )


    ax =axes [1 ]
    sns .barplot (
    data =df_plot ,x ='Scenario_Label',y ='Accuracy',hue ='Model',
    order =scenario_label_order ,ax =ax ,edgecolor ='black',linewidth =0.5 
    )
    ax .set_title (f'Accuracy Degradation [{mode_label }]',fontweight ='bold')
    ax .set_xlabel ('Test Scenario')
    ax .set_ylabel ('Accuracy')
    ax .set_ylim (0 ,1.05 )
    ax .legend (title ='Model',loc ='lower left',framealpha =0.9 )

    for container in ax .containers :
        ax .bar_label (container ,fmt ='%.2f',fontsize =7 ,padding =2 ,rotation =90 )

    plt .tight_layout ()
    path =os .path .join (output_dir ,f'plot1_robustness_degradation_{mode }.png')
    plt .savefig (path ,bbox_inches ='tight')
    plt .close ()
    print (f"    Saved: {path }")


    fig ,ax =plt .subplots (figsize =(10 ,5 ))
    pivot =df_plot .pivot_table (index ='Model',columns ='Scenario_Label',
    values ='F1_Macro',aggfunc ='first')
    pivot =pivot [scenario_label_order ]
    sns .heatmap (pivot ,annot =True ,fmt ='.3f',cmap ='RdYlGn',vmin =0 ,vmax =1 ,
    linewidths =0.5 ,ax =ax ,cbar_kws ={'label':'F1-Macro'})
    ax .set_title (f'F1-Macro Heatmap: Model × Scenario [{mode_label }]',fontweight ='bold')
    plt .tight_layout ()
    path_hm =os .path .join (output_dir ,f'plot1b_heatmap_f1macro_{mode }.png')
    plt .savefig (path_hm ,bbox_inches ='tight')
    plt .close ()
    print (f"    Saved: {path_hm }")


def plot_radar_chart (all_results ,label_encoder ,output_dir ,mode ='multiclass'):
    """
    Graph 2: Radar / Spider plot for the best model under Scenario D (Nightmare).
    Shows per-class F1-score. Only generated for multiclass mode (binary has only 2 axes).
    """
    mode_label =mode .upper ()
    scenario_d_name =STRESS_SCENARIOS .get ('Scenario_D',{}).get ('name','Scenario D')
    print (f"\n  Generating Plot 2: Radar Chart (Scenario D - {scenario_d_name }) [{mode_label }]...")

    if mode =='binary':

        results_d =[r for r in all_results if r ['Scenario']=='Scenario_D']
        if not results_d :
            print ("    [SKIP] Scenario D not found.")
            return 

        fig ,ax =plt .subplots (figsize =(10 ,6 ))
        models =[]
        benign_f1 =[]
        attack_f1 =[]
        for r in results_d :
            models .append (r ['Model'])
            benign_f1 .append (r ['Report'].get (BENIGN_LABEL ,{}).get ('f1-score',0.0 ))
            attack_f1 .append (r ['Report'].get ('ATTACK',{}).get ('f1-score',0.0 ))

        x =np .arange (len (models ))
        width =0.35 
        ax .bar (x -width /2 ,benign_f1 ,width ,label =BENIGN_LABEL ,color ='#2ecc71',edgecolor ='black',linewidth =0.5 )
        ax .bar (x +width /2 ,attack_f1 ,width ,label ='ATTACK',color ='#e74c3c',edgecolor ='black',linewidth =0.5 )
        ax .set_xlabel ('Model')
        ax .set_ylabel ('F1-Score')
        ax .set_title (f'Per-Class F1-Score Under Scenario D ({scenario_d_name }) [BINARY]',fontweight ='bold')
        ax .set_xticks (x )
        ax .set_xticklabels (models ,rotation =15 )
        ax .set_ylim (0 ,1.05 )
        ax .legend ()
        for i ,(b ,a )in enumerate (zip (benign_f1 ,attack_f1 )):
            ax .text (i -width /2 ,b +0.02 ,f'{b :.3f}',ha ='center',fontsize =8 )
            ax .text (i +width /2 ,a +0.02 ,f'{a :.3f}',ha ='center',fontsize =8 )

        plt .tight_layout ()
        path =os .path .join (output_dir ,'plot2_binary_f1_scenario_d.png')
        plt .savefig (path ,bbox_inches ='tight')
        plt .close ()
        print (f"    Saved: {path }")
        return 


    results_d =[r for r in all_results if r ['Scenario']=='Scenario_D']
    if not results_d :
        print ("    [SKIP] Scenario D not found.")
        return 


    best_d =max (results_d ,key =lambda x :x ['F1_Macro'])
    print (f"    Best model on Scenario D: {best_d ['Model']} (F1-Macro={best_d ['F1_Macro']:.4f})")


    report_data ={}
    for r in results_d :
        class_f1 ={}
        for cls_name in label_encoder .classes_ :
            if cls_name in r ['Report']:
                class_f1 [cls_name ]=r ['Report'][cls_name ]['f1-score']
            else :
                class_f1 [cls_name ]=0.0 
        report_data [r ['Model']]=class_f1 

    categories =list (label_encoder .classes_ )
    N =len (categories )
    angles =[n /float (N )*2 *math .pi for n in range (N )]
    angles +=angles [:1 ]

    fig ,ax =plt .subplots (figsize =(9 ,9 ),subplot_kw =dict (polar =True ))

    colors =plt .cm .Set2 (np .linspace (0 ,1 ,len (report_data )))

    for idx ,(model_name ,class_f1 )in enumerate (report_data .items ()):
        values =[class_f1 .get (cat ,0.0 )for cat in categories ]
        values +=values [:1 ]

        linewidth =2.5 if model_name ==best_d ['Model']else 1.2 
        alpha_fill =0.15 if model_name ==best_d ['Model']else 0.05 

        ax .plot (angles ,values ,'o-',linewidth =linewidth ,
        label =model_name ,color =colors [idx ])
        ax .fill (angles ,values ,alpha =alpha_fill ,color =colors [idx ])

    ax .set_xticks (angles [:-1 ])
    ax .set_xticklabels (categories ,fontsize =10 )
    ax .set_ylim (0 ,1.0 )
    ax .set_yticks ([0.2 ,0.4 ,0.6 ,0.8 ,1.0 ])
    ax .set_yticklabels (['0.2','0.4','0.6','0.8','1.0'],fontsize =8 ,color ='grey')
    ax .set_title (f'Per-Class F1-Score Under Scenario D ({scenario_d_name })\nAll Models [MULTICLASS]',
    fontweight ='bold',pad =20 )
    ax .legend (loc ='upper right',bbox_to_anchor =(1.35 ,1.1 ),framealpha =0.9 )

    plt .tight_layout ()
    path =os .path .join (output_dir ,'plot2_radar_scenario_d_multiclass.png')
    plt .savefig (path ,bbox_inches ='tight')
    plt .close ()
    print (f"    Saved: {path }")


def plot_confusion_matrix_botnet (all_results ,label_encoder ,output_dir ,mode ='multiclass'):
    """
    Graph 3: Confusion matrix of the best model under Scenario B.
    """
    mode_label =mode .upper ()
    scenario_b_name =STRESS_SCENARIOS .get ('Scenario_B',{}).get ('name','Scenario B')
    scenario_d_name =STRESS_SCENARIOS .get ('Scenario_D',{}).get ('name','Scenario D')
    print (f"\n  Generating Plot 3: Confusion Matrix (Scenario B - {scenario_b_name }) [{mode_label }]...")

    results_b =[r for r in all_results if r ['Scenario']=='Scenario_B']
    if not results_b :
        print ("    [SKIP] Scenario B not found.")
        return 

    best_b =max (results_b ,key =lambda x :x ['F1_Macro'])
    print (f"    Best model on Scenario B: {best_b ['Model']} (F1-Macro={best_b ['F1_Macro']:.4f})")

    cm =best_b ['Confusion_Matrix']



    class_names =label_encoder .classes_ 

    fig ,axes =plt .subplots (1 ,2 ,figsize =(18 ,7 ))


    ax =axes [0 ]
    sns .heatmap (
    pd .DataFrame (cm ,index =class_names ,columns =class_names ),
    annot =True ,fmt ='d',cmap ='Blues',ax =ax ,
    linewidths =0.5 ,cbar_kws ={'label':'Count'}
    )
    ax .set_title (f'Confusion Matrix (Counts)\n{best_b ["Model"]} on Scenario B: {scenario_b_name } [{mode_label }]',
    fontweight ='bold')
    ax .set_xlabel ('Predicted')
    ax .set_ylabel ('True')


    ax =axes [1 ]
    cm_norm =cm .astype (float )
    row_sums =cm_norm .sum (axis =1 ,keepdims =True )
    row_sums [row_sums ==0 ]=1 
    cm_norm =cm_norm /row_sums 

    sns .heatmap (
    pd .DataFrame (cm_norm ,index =class_names ,columns =class_names ),
    annot =True ,fmt ='.2%',cmap ='Oranges',ax =ax ,
    linewidths =0.5 ,vmin =0 ,vmax =1 ,cbar_kws ={'label':'Rate'}
    )
    ax .set_title (f'Confusion Matrix (Normalized by True Class)\n{best_b ["Model"]} on Scenario B: {scenario_b_name } [{mode_label }]',
    fontweight ='bold')
    ax .set_xlabel ('Predicted')
    ax .set_ylabel ('True')

    plt .tight_layout ()
    path =os .path .join (output_dir ,f'plot3_confusion_matrix_botnet_{mode }.png')
    plt .savefig (path ,bbox_inches ='tight')
    plt .close ()
    print (f"    Saved: {path }")


    results_d =[r for r in all_results if r ['Scenario']=='Scenario_D']
    if results_d :
        best_overall =max (results_d ,key =lambda x :x ['F1_Macro'])
        cm_d =best_overall ['Confusion_Matrix']

        fig ,ax =plt .subplots (figsize =(9 ,7 ))
        cm_d_norm =cm_d .astype (float )
        row_sums_d =cm_d_norm .sum (axis =1 ,keepdims =True )
        row_sums_d [row_sums_d ==0 ]=1 
        cm_d_norm =cm_d_norm /row_sums_d 

        sns .heatmap (
        pd .DataFrame (cm_d_norm ,index =class_names ,columns =class_names ),
        annot =True ,fmt ='.2%',cmap ='Reds',ax =ax ,
        linewidths =0.5 ,vmin =0 ,vmax =1 ,cbar_kws ={'label':'Rate'}
        )
        ax .set_title (f'Confusion Matrix (Normalized)\n{best_overall ["Model"]} on Scenario D: {scenario_d_name } [{mode_label }]',
        fontweight ='bold')
        ax .set_xlabel ('Predicted')
        ax .set_ylabel ('True')
        plt .tight_layout ()
        path_d =os .path .join (output_dir ,f'plot3b_confusion_matrix_nightmare_{mode }.png')
        plt .savefig (path_d ,bbox_inches ='tight')
        plt .close ()
        print (f"    Saved: {path_d }")


def _plot_multiclass_vs_binary (results_multi ,results_binary ,output_dir ):
    """
    Comparative plot: side-by-side F1-Macro for multiclass vs binary across scenarios.
    """
    plots_dir =os .path .join (output_dir ,'plots')
    os .makedirs (plots_dir ,exist_ok =True )

    scenario_order =['Real_Test','Scenario_A','Scenario_B','Scenario_C','Scenario_D']
    scenario_labels =build_scenario_labels (multiline =False )

    rows =[]
    for r in results_multi :
        rows .append ({'Model':r ['Model'],'Scenario':r ['Scenario'],
        'F1_Macro':r ['F1_Macro'],'Accuracy':r ['Accuracy'],'Mode':'Multiclass'})
    for r in results_binary :
        rows .append ({'Model':r ['Model'],'Scenario':r ['Scenario'],
        'F1_Macro':r ['F1_Macro'],'Accuracy':r ['Accuracy'],'Mode':'Binary'})

    df_cmp =pd .DataFrame (rows )
    present_scenarios =[s for s in scenario_order if s in df_cmp ['Scenario'].values ]
    df_cmp ['Scenario_Label']=df_cmp ['Scenario'].map (scenario_labels )
    scenario_label_order =[scenario_labels [s ]for s in present_scenarios ]


    models =list (VICTIM_MODELS .keys ())
    n_models =len (models )
    fig ,axes =plt .subplots (1 ,n_models ,figsize =(5 *n_models ,6 ),sharey =True )
    if n_models ==1 :
        axes =[axes ]

    for idx ,model_name in enumerate (models ):
        ax =axes [idx ]
        df_model =df_cmp [df_cmp ['Model']==model_name ]
        sns .barplot (
        data =df_model ,x ='Scenario_Label',y ='F1_Macro',hue ='Mode',
        order =scenario_label_order ,ax =ax ,edgecolor ='black',linewidth =0.5 ,
        palette ={'Multiclass':'#3498db','Binary':'#e74c3c'}
        )
        ax .set_title (model_name ,fontweight ='bold')
        ax .set_xlabel ('')
        ax .set_ylabel ('F1-Macro'if idx ==0 else '')
        ax .set_ylim (0 ,1.05 )
        ax .tick_params (axis ='x',rotation =30 )
        if idx >0 :
            ax .get_legend ().remove ()
        else :
            ax .legend (title ='Mode',loc ='lower left',framealpha =0.9 )

        for container in ax .containers :
            ax .bar_label (container ,fmt ='%.2f',fontsize =6 ,padding =2 ,rotation =90 )

    fig .suptitle ('Multiclass vs Binary: F1-Macro Comparison Per Model',fontweight ='bold',fontsize =14 ,y =1.02 )
    plt .tight_layout ()
    path =os .path .join (plots_dir ,'plot_comparison_multiclass_vs_binary.png')
    plt .savefig (path ,bbox_inches ='tight')
    plt .close ()
    print (f"    Saved: {path }")


    fig ,ax =plt .subplots (figsize =(10 ,5 ))
    pivot_multi =df_cmp [df_cmp ['Mode']=='Multiclass'].pivot_table (
    index ='Model',columns ='Scenario_Label',values ='F1_Macro',aggfunc ='first'
    )
    pivot_binary =df_cmp [df_cmp ['Mode']=='Binary'].pivot_table (
    index ='Model',columns ='Scenario_Label',values ='F1_Macro',aggfunc ='first'
    )
    common_cols =[c for c in scenario_label_order if c in pivot_multi .columns and c in pivot_binary .columns ]
    delta =pivot_binary [common_cols ]-pivot_multi [common_cols ]
    sns .heatmap (delta ,annot =True ,fmt ='+.3f',cmap ='RdBu',center =0 ,
    linewidths =0.5 ,ax =ax ,cbar_kws ={'label':'Δ F1-Macro (Binary − Multiclass)'})
    ax .set_title ('F1-Macro Difference: Binary − Multiclass',fontweight ='bold')
    plt .tight_layout ()
    path_delta =os .path .join (plots_dir ,'plot_delta_binary_vs_multiclass.png')
    plt .savefig (path_delta ,bbox_inches ='tight')
    plt .close ()
    print (f"    Saved: {path_delta }")


def plot_stress_test_overview (all_results ,scenarios_dist ,output_dir ,mode ='multiclass'):
    import matplotlib .ticker as mticker 
    from matplotlib .patches import Patch 
    import seaborn as sns 
    mode_label =mode .upper ()
    print (f"\n  Generating Plot 4 & 5 Combined: Overview [{mode_label }]...")

    fig ,axes =plt .subplots (1 ,2 ,figsize =(15 ,6 ))




    ax0 =axes [0 ]
    scenario_order =['Scenario_D','Scenario_C','Scenario_B','Scenario_A']
    present_scenarios =[s for s in scenario_order if s in scenarios_dist ]

    all_classes =[]
    for s in present_scenarios :
        all_classes .extend (scenarios_dist [s ]['distribution'].keys ())
    all_classes =list (set (all_classes ))
    all_classes .sort ()

    colors =sns .color_palette ("husl",len (all_classes ))
    class_colors =dict (zip (all_classes ,colors ))

    scenario_labels_a =build_scenario_labels (multiline =True ,include_name =True )
    y =np .arange (len (present_scenarios ))

    for i ,s_id in enumerate (present_scenarios ):
        counts =scenarios_dist [s_id ]['distribution']
        total =sum (counts .values ())
        left =0 
        for cls in all_classes :
            if cls in counts and counts [cls ]>0 :
                count =counts [cls ]
                pct =count /total 
                ax0 .barh (i ,pct ,left =left ,color =class_colors [cls ],edgecolor ='white',linewidth =0.5 )
                if pct >0.05 :
                    luminance =0.299 *class_colors [cls ][0 ]+0.587 *class_colors [cls ][1 ]+0.114 *class_colors [cls ][2 ]
                    textcolor ='white'if luminance <0.6 else 'black'
                    ax0 .text (left +pct /2 ,i ,f'{int (pct *100 )}%',ha ='center',va ='center',color =textcolor ,fontweight ='bold',fontsize =9 )
                left +=pct 
        ax0 .text (1.02 ,i ,f'n={int (total /1000 )}K',va ='center',fontweight ='bold')

    labels_a =[scenario_labels_a .get (s ,s )for s in present_scenarios ]

    ax0 .set_yticks (y )
    ax0 .set_yticklabels (labels_a )
    ax0 .set_xlabel ('Proportion',fontweight ='bold')
    ax0 .set_xlim (0 ,1 )
    ax0 .xaxis .set_major_formatter (mticker .PercentFormatter (1.0 ))
    ax0 .set_title ('(a) Scenario Composition',fontweight ='bold',fontsize =14 )

    handles =[Patch (color =class_colors [cls ],label =cls )for cls in all_classes ]
    ax0 .legend (handles =handles ,loc ='upper center',bbox_to_anchor =(0.5 ,-0.15 ),ncol =4 ,frameon =False ,fontsize =9 )




    ax1 =axes [1 ]
    df_res =pd .DataFrame ([{
    'Model':r ['Model'],
    'Scenario':r ['Scenario'],
    'F1_Macro':r ['F1_Macro']
    }for r in all_results ])

    scenario_order_b =['Real_Test','Scenario_A','Scenario_B','Scenario_C','Scenario_D']
    scenario_labels_b =build_scenario_labels (multiline =True )
    present_scenarios_b =[s for s in scenario_order_b if s in df_res ['Scenario'].values ]

    markers =['o','s','D','^','v','<','>']
    models =df_res ['Model'].unique ()

    b_colors =sns .color_palette ("deep",len (models ))
    for i ,model in enumerate (models ):
        model_data =df_res [df_res ['Model']==model ].set_index ('Scenario')
        y_vals =[model_data .loc [s ,'F1_Macro']if s in model_data .index else np .nan for s in present_scenarios_b ]
        ax1 .plot (range (len (present_scenarios_b )),y_vals ,marker =markers [i %len (markers )],color =b_colors [i ],linewidth =2 ,markersize =8 ,label =model )

    ax1 .axhline (0.5 ,color ='salmon',linestyle ='--',linewidth =1 )
    if present_scenarios_b :
        ax1 .text (len (present_scenarios_b )-1.2 ,0.52 ,'Usability\nthreshold',color ='salmon',fontsize =9 ,fontstyle ='italic')
    ax1 .axhspan (0 ,0.1 ,color ='mistyrose',alpha =0.3 )

    ax1 .set_xticks (range (len (present_scenarios_b )))
    ax1 .set_xticklabels ([scenario_labels_b [s ]for s in present_scenarios_b ],fontsize =10 )
    ax1 .set_ylabel ('F1-Macro',fontweight ='bold')
    ax1 .set_title ('(b) Multiclass Robustness Trajectory',fontweight ='bold',fontsize =14 )
    ax1 .set_ylim (-0.05 ,1.05 )

    ax1 .legend (loc ='upper center',bbox_to_anchor =(0.5 ,-0.15 ),ncol =4 ,frameon =False ,fontsize =9 )

    sns .despine (ax =ax0 ,top =True ,right =True ,left =True )
    sns .despine (ax =ax1 ,top =True ,right =True )

    plt .tight_layout ()
    path_pdf =os .path .join (output_dir ,f'plot_overview_{mode }.pdf')
    path_png =os .path .join (output_dir ,f'plot_overview_{mode }.png')
    plt .savefig (path_pdf ,bbox_inches ='tight',dpi =500 )
    plt .savefig (path_png ,bbox_inches ='tight',dpi =500 )
    plt .close ()
    print (f"    Saved: {path_pdf } and .png")


def plot_scenario_composition (scenarios ,output_dir ,mode ='multiclass'):
    import matplotlib .ticker as mticker 
    mode_label =mode .upper ()
    print (f"\n  Generating Plot 5: Scenario Composition [{mode_label }]...")

    fig ,ax =plt .subplots (figsize =(10 ,5 ))
    scenario_order =['Scenario_D','Scenario_C','Scenario_B','Scenario_A']
    present_scenarios =[s for s in scenario_order if s in scenarios ]
    if not present_scenarios :return 

    y =np .arange (len (present_scenarios ))
    all_classes =[]
    for s in present_scenarios :
        all_classes .extend (scenarios [s ]['Label_Class'].unique ())
    all_classes =list (set (all_classes ))
    all_classes .sort ()


    cmap =plt .cm .get_cmap ('tab20')
    colors =cmap (np .linspace (0 ,1 ,len (all_classes )))
    class_colors =dict (zip (all_classes ,colors ))

    for i ,s_id in enumerate (present_scenarios ):
        df =scenarios [s_id ]
        total =len (df )
        counts =df ['Label_Class'].value_counts ()
        left =0 
        for cls in all_classes :
            if cls in counts :
                count =counts [cls ]
                pct =count /total 
                ax .barh (i ,pct ,left =left ,color =class_colors [cls ],edgecolor ='white')
                if pct >0.05 :
                    textcolor ='white'if np .mean (class_colors [cls ][:3 ])<0.6 else 'black'
                    ax .text (left +pct /2 ,i ,f'{int (pct *100 )}%',ha ='center',va ='center',color =textcolor ,fontweight ='bold',fontsize =9 )
                left +=pct 
        ax .text (1.02 ,i ,f'n={int (total /1000 )}K',va ='center',fontweight ='bold')

    ax .set_yticks (y )
    scenario_labels =build_scenario_labels (multiline =True ,include_name =True )
    labels =[scenario_labels .get (s ,s )for s in present_scenarios ]
    ax .set_yticklabels (labels )
    ax .set_xlabel ('Proportion',fontweight ='bold')
    ax .set_xlim (0 ,1 )
    ax .xaxis .set_major_formatter (mticker .PercentFormatter (1.0 ))
    ax .set_title ('(a) Scenario Composition',fontweight ='bold',fontsize =14 )

    from matplotlib .patches import Patch 
    handles =[Patch (color =class_colors [cls ],label =cls )for cls in all_classes ]
    ax .legend (handles =handles ,loc ='upper center',bbox_to_anchor =(0.5 ,-0.15 ),ncol =7 ,frameon =False ,fontsize =9 )

    sns .despine (top =True ,right =True ,left =True )
    plt .tight_layout ()
    path =os .path .join (output_dir ,f'plot5_scenario_composition_{mode }.png')
    plt .savefig (path ,bbox_inches ='tight')
    plt .close ()
    print (f"    Saved: {path }")


def generate_all_plots (all_results ,label_encoder ,output_dir ,mode ='multiclass',scenarios =None ):
    """Generate all paper-ready visualizations for a given mode."""
    mode_label =mode .upper ()
    print ("\n"+"="*70 )
    print (f"[PHASE 4] GENERATING PAPER-READY VISUALIZATIONS [{mode_label }]")
    print ("="*70 )

    plots_dir =os .path .join (output_dir ,'plots')
    os .makedirs (plots_dir ,exist_ok =True )

    set_paper_style ()

    plot_robustness_degradation (all_results ,plots_dir ,mode =mode )
    plot_radar_chart (all_results ,label_encoder ,plots_dir ,mode =mode )
    plot_confusion_matrix_botnet (all_results ,label_encoder ,plots_dir ,mode =mode )
    plot_stress_test_overview (all_results ,STRESS_SCENARIOS ,plots_dir ,mode =mode )


    print (f"\n  [OK] All {mode_label } plots saved to: {plots_dir }")






def save_results_csv (all_results ,output_dir ,mode ='multiclass'):
    """Save all numerical results to CSV for reproducibility."""
    mode_label =mode .upper ()
    class_list =ALL_CLASSES if mode =='multiclass'else BINARY_CLASSES 

    rows =[]
    for r in all_results :
        row ={
        'Mode':mode ,
        'Model':r ['Model'],
        'Scenario':r ['Scenario'],
        'Scenario_Name':STRESS_SCENARIOS .get (r ['Scenario'],{}).get ('name','Real Test'),
        'Test_Samples':r ['Test_Samples'],
        'Accuracy':r ['Accuracy'],
        'F1_Macro':r ['F1_Macro'],
        'F1_Weighted':r ['F1_Weighted'],
        'Precision_Macro':r ['Precision_Macro'],
        'Recall_Macro':r ['Recall_Macro'],
        }


        for cls_name in class_list :
            if cls_name in r ['Report']:
                row [f'F1_{cls_name }']=r ['Report'][cls_name ]['f1-score']
                row [f'Precision_{cls_name }']=r ['Report'][cls_name ]['precision']
                row [f'Recall_{cls_name }']=r ['Report'][cls_name ]['recall']

        rows .append (row )

    df =pd .DataFrame (rows )
    csv_path =os .path .join (output_dir ,f'stress_test_results_{mode }.csv')
    df .to_csv (csv_path ,index =False )
    print (f"\n  [SAVED] {mode_label } Results CSV: {csv_path }")


    for r in all_results :
        report_df =pd .DataFrame (r ['Report']).transpose ()
        fname =f"{r ['Model']}_{r ['Scenario']}_{mode }_classification_report.csv"
        report_df .to_csv (os .path .join (output_dir ,fname ))


    for r in all_results :
        cm_labels =class_list if r ['Confusion_Matrix'].shape [0 ]==len (class_list )else [
        f'Class_{i }'for i in range (r ['Confusion_Matrix'].shape [0 ])
        ]
        cm_df =pd .DataFrame (
        r ['Confusion_Matrix'],
        index =cm_labels ,
        columns =cm_labels 
        )
        fname =f"{r ['Model']}_{r ['Scenario']}_{mode }_confusion_matrix.csv"
        cm_df .to_csv (os .path .join (output_dir ,fname ))

    return df 


def generate_text_summary (all_results ,label_encoder ,output_dir ,mode ='multiclass'):
    """Generate a comprehensive text summary of all results for a given mode."""
    mode_label =mode .upper ()
    lines =[]
    lines .append ("="*120 )
    lines .append (" "*20 +f"NIDS ROBUSTNESS AUDIT - STRESS TESTING RESULTS [{mode_label }]")
    lines .append (" "*20 +"Train on Real Data → Test on GAN-Generated Adversarial Traffic")
    lines .append (f" "*40 +f"Date: {datetime .now ().strftime ('%Y-%m-%d %H:%M:%S')}")
    lines .append ("="*120 )


    lines .append ("\n"+"="*120 )
    lines .append ("1. EXPERIMENT OVERVIEW")
    lines .append ("="*120 )
    lines .append (f"\n  Models evaluated: {', '.join (VICTIM_MODELS .keys ())}")
    lines .append (f"  Scenarios: Real Test + {len (STRESS_SCENARIOS )} adversarial scenarios")
    for sid ,scfg in STRESS_SCENARIOS .items ():
        total_s =sum (scfg ['distribution'].values ())
        lines .append (f"    {sid } ({scfg ['name']}): {total_s :,} samples")
        if mode =='multiclass':
            for cls ,n in scfg ['distribution'].items ():
                lines .append (f"      {cls :<15}: {n :>10,} ({n /total_s *100 :>5.1f}%)")
        else :
            benign_n =scfg ['distribution'].get (BENIGN_LABEL ,0 )
            attack_n =total_s -benign_n 
            lines .append (f"      {BENIGN_LABEL :<15}: {benign_n :>10,} ({benign_n /total_s *100 :>5.1f}%)")
            lines .append (f"      {'ATTACK':<15}: {attack_n :>10,} ({attack_n /total_s *100 :>5.1f}%)")


    lines .append ("\n\n"+"="*120 )
    lines .append (f"2. MODEL RANKINGS PER SCENARIO [{mode_label }] (by F1-Macro)")
    lines .append ("="*120 )

    scenarios_seen =sorted (set (r ['Scenario']for r in all_results ),
    key =lambda x :['Real_Test','Scenario_A','Scenario_B',
    'Scenario_C','Scenario_D'].index (x )
    if x in ['Real_Test','Scenario_A','Scenario_B',
    'Scenario_C','Scenario_D']else 99 )

    for scenario in scenarios_seen :
        scfg =STRESS_SCENARIOS .get (scenario ,{'name':'Real Test'})
        s_name =scfg .get ('name','Real Test')
        results_s =sorted ([r for r in all_results if r ['Scenario']==scenario ],
        key =lambda x :x ['F1_Macro'],reverse =True )

        lines .append (f"\n  {'─'*100 }")
        lines .append (f"  {scenario } ({s_name })")
        lines .append (f"  {'─'*100 }")
        lines .append (f"  {'Pos':<5} {'Model':<15} │ {'Accuracy':>10} {'F1-Macro':>10} "
        f"{'F1-Weight':>10} │ {'Precision':>10} {'Recall':>10}")
        lines .append (f"  {'─'*80 }")

        for i ,r in enumerate (results_s ,1 ):
            lines .append (f"  {i :<5} {r ['Model']:<15} │ {r ['Accuracy']:>10.4f} {r ['F1_Macro']:>10.4f} "
            f"{r ['F1_Weighted']:>10.4f} │ {r ['Precision_Macro']:>10.4f} {r ['Recall_Macro']:>10.4f}")


    lines .append ("\n\n"+"="*120 )
    lines .append (f"3. ROBUSTNESS DEGRADATION ANALYSIS [{mode_label }] (Δ vs Real Test)")
    lines .append ("="*120 )

    real_results ={r ['Model']:r for r in all_results if r ['Scenario']=='Real_Test'}

    lines .append (f"\n  {'Model':<15} │ {'Scenario':<25} │ {'Δ Accuracy':>12} {'Δ F1-Macro':>12} "
    f"{'Δ Precision':>12} {'Δ Recall':>12}")
    lines .append (f"  {'─'*100 }")

    for r in all_results :
        if r ['Scenario']=='Real_Test':
            continue 
        baseline =real_results .get (r ['Model'])
        if baseline :
            d_acc =r ['Accuracy']-baseline ['Accuracy']
            d_f1 =r ['F1_Macro']-baseline ['F1_Macro']
            d_prec =r ['Precision_Macro']-baseline ['Precision_Macro']
            d_rec =r ['Recall_Macro']-baseline ['Recall_Macro']

            s_name =STRESS_SCENARIOS .get (r ['Scenario'],{}).get ('name',r ['Scenario'])
            lines .append (f"  {r ['Model']:<15} │ {s_name :<25} │ {d_acc :>+12.4f} {d_f1 :>+12.4f} "
            f"{d_prec :>+12.4f} {d_rec :>+12.4f}")


    lines .append ("\n\n"+"="*120 )
    lines .append (f"4. KEY FINDINGS [{mode_label }]")
    lines .append ("="*120 )


    model_degradation ={}
    for model_name in VICTIM_MODELS :
        baseline =real_results .get (model_name )
        if not baseline :
            continue 
        deltas =[]
        for r in all_results :
            if r ['Model']==model_name and r ['Scenario']!='Real_Test':
                deltas .append (abs (r ['F1_Macro']-baseline ['F1_Macro']))
        if deltas :
            model_degradation [model_name ]=np .mean (deltas )

    if model_degradation :
        most_robust =min (model_degradation ,key =model_degradation .get )
        least_robust =max (model_degradation ,key =model_degradation .get )
        lines .append (f"\n  Most robust model:  {most_robust } "
        f"(avg Δ F1-Macro = {model_degradation [most_robust ]:+.4f})")
        lines .append (f"  Least robust model: {least_robust } "
        f"(avg Δ F1-Macro = {model_degradation [least_robust ]:+.4f})")


    lines .append (f"\n  Worst scenario per model:")
    for model_name in VICTIM_MODELS :
        model_results =[r for r in all_results 
        if r ['Model']==model_name and r ['Scenario']!='Real_Test']
        if model_results :
            worst =min (model_results ,key =lambda x :x ['F1_Macro'])
            s_name =STRESS_SCENARIOS .get (worst ['Scenario'],{}).get ('name',worst ['Scenario'])
            lines .append (f"    {model_name :<15}: {s_name :<25} F1-Macro = {worst ['F1_Macro']:.4f}")

    lines .append ("\n"+"="*120 )

    summary_text ="\n".join (lines )

    path =os .path .join (output_dir ,f'STRESS_TEST_SUMMARY_{mode }.txt')
    with open (path ,'w')as f :
        f .write (summary_text )

    print (f"\n{summary_text }")
    print (f"\n  [SAVED] {mode_label } Summary: {path }")






def main ():
    parser =argparse .ArgumentParser (
    description ='NIDS Robustness Audit: Stress-Testing with GAN-Generated Adversarial Traffic',
    formatter_class =argparse .RawDescriptionHelpFormatter ,
    epilog ="""
Examples:
  # Full experiment (all phases)
  python stress_test_nids.py

  # Specify test size
  python stress_test_nids.py --test-size 0.3

  # Custom output directory
  python stress_test_nids.py --output results_stress_test/my_run
        """
    )

    parser .add_argument ('--dataset',type =str ,default ='cicids2017',
    choices =list (DATASETS .keys ()),
    help ='Dataset to use (default: cicids2017)')
    parser .add_argument ('--test-size',type =float ,default =0.3 ,
    help ='Proportion of real data for test set (default: 0.3)')
    parser .add_argument ('--output',type =str ,default =None ,
    help ='Custom output directory')
    parser .add_argument ('--skip-plots',action ='store_true',
    help ='Skip plot generation')
    parser .add_argument ('--gpu',type =str ,default ='0',
    help ='GPU to use for GAN inference (default: 0)')
    parser .add_argument ('--fast',action ='store_true',
    help ='Use faster/lighter model hyperparameters')
    parser .add_argument ('--load-results',type =str ,default =None ,
    help ='Load results from an existing directory instead of re-running the test')


    args =parser .parse_args ()


    os .environ ["CUDA_VISIBLE_DEVICES"]=args .gpu 
    set_dataset (args .dataset )

    global VICTIM_MODELS 
    VICTIM_MODELS =build_victim_models (fast =args .fast )




    if args .load_results :
        output_dir =args .load_results 
        print (f"\n  [!] Loading existing results from: {output_dir }")
        print_header ()


        label_encoder_multi =LabelEncoder ().fit (ALL_CLASSES )

        def load_mode_results (mode ,class_list ):
            import pandas as pd 
            import numpy as np 
            csv_path =os .path .join (output_dir ,f'stress_test_results_{mode }.csv')
            if not os .path .exists (csv_path ):return []
            df =pd .read_csv (csv_path )
            res =df .to_dict ('records')
            for r in res :
                rep_path =os .path .join (output_dir ,f"{r ['Model']}_{r ['Scenario']}_{mode }_classification_report.csv")
                r ['Report']=pd .read_csv (rep_path ,index_col =0 ).to_dict ('index')if os .path .exists (rep_path )else {}
                cm_path =os .path .join (output_dir ,f"{r ['Model']}_{r ['Scenario']}_{mode }_confusion_matrix.csv")
                r ['Confusion_Matrix']=pd .read_csv (cm_path ,index_col =0 ).values if os .path .exists (cm_path )else np .zeros ((len (class_list ),len (class_list )))
            return res 

        results_multi =load_mode_results ('multiclass',ALL_CLASSES )

        if not args .skip_plots :
            generate_all_plots (results_multi ,label_encoder_multi ,output_dir ,mode ='multiclass')

        print (f"\n{'='*100 }")
        print ("  GRAPHICS REGENERATION COMPLETE")
        print (f"{'='*100 }\n")
        return 

    if args .output :
        output_dir =args .output 
    else :
        timestamp =datetime .now ().strftime ("%Y%m%d_%H%M%S")
        output_dir =os .path .join (OUTPUT_DIR ,f'stress_test_{timestamp }')
    os .makedirs (output_dir ,exist_ok =True )

    print_header ()
    print (f"\n  Output directory: {output_dir }")
    print (f"  Fast mode: {'ON'if args .fast else 'OFF'}")


    config ={
    'timestamp':datetime .now ().isoformat (),
    'test_size':args .test_size ,
    'models_dir':MODELS_DIR ,
    'random_state':RANDOM_STATE ,
    'models':list (VICTIM_MODELS .keys ()),
    'fast_mode':args .fast ,
    'scenarios':{k :v ['distribution']for k ,v in STRESS_SCENARIOS .items ()},
    'modes':['multiclass'],
    }
    with open (os .path .join (output_dir ,'experiment_config.json'),'w')as f :
        json .dump (config ,f ,indent =2 )

    start_total =datetime .now ()




    df_raw =load_real_data ()
    df_features =prepare_features (df_raw ,target_classes =ALL_CLASSES )

    print (f"\n  Filtered dataset: {len (df_features ):,} samples")
    print (f"  Classes (multiclass): {ALL_CLASSES }")
    print (f"\n  Multiclass Distribution:")
    for cls in ALL_CLASSES :
        cnt =len (df_features [df_features ['Label_Class']==cls ])
        pct =(cnt /len (df_features ))*100 
        print (f"    {cls :<15}: {cnt :>10,} ({pct :>5.1f}%)")

    feature_cols =[c for c in df_features .columns if c !='Label_Class']
    X =df_features [feature_cols ].values 


    label_encoder_multi =LabelEncoder ()
    label_encoder_multi .fit (ALL_CLASSES )
    y_multi =label_encoder_multi .transform (df_features ['Label_Class'])

    print (f"\n  Features: {len (feature_cols )}")
    print (f"  Multiclass encoded classes: {list (label_encoder_multi .classes_ )}")


    X_train ,X_test ,y_train_multi ,y_test_multi =train_test_split (
    X ,y_multi ,
    test_size =args .test_size ,
    random_state =RANDOM_STATE ,
    stratify =y_multi 
    )
    print (f"\n  Train: {len (X_train ):,} | Test: {len (X_test ):,}")


    scaler =MinMaxScaler ()
    scaler .fit (X_train )
    X_train_clean =np .nan_to_num (X_train ,nan =0 ,posinf =0 ,neginf =0 )




    trained_models_multi =train_victim_models (X_train_clean ,y_train_multi ,scaler ,mode ='multiclass')




    scenarios =generate_stress_scenarios ()




    results_multi =run_massive_evaluation (
    trained_models_multi ,scaler ,label_encoder_multi ,
    X_test ,y_test_multi ,
    scenarios ,output_dir ,mode ='multiclass'
    )



    results_df_multi =save_results_csv (results_multi ,output_dir ,mode ='multiclass')




    if not args .skip_plots :
        generate_all_plots (results_multi ,label_encoder_multi ,output_dir ,mode ='multiclass',scenarios =scenarios )




    generate_text_summary (results_multi ,label_encoder_multi ,output_dir ,mode ='multiclass')

    elapsed_total =datetime .now ()-start_total 
    print (f"\n{'='*100 }")
    print (f"  EXPERIMENT COMPLETED IN {elapsed_total }")
    print (f"  Results: {output_dir }")
    print (f"  CSV (multiclass): {os .path .join (output_dir ,'stress_test_results_multiclass.csv')}")
    print (f"  Plots:            {os .path .join (output_dir ,'plots/')}")
    print (f"  Summary (multi):  {os .path .join (output_dir ,'STRESS_TEST_SUMMARY_multiclass.txt')}")
    print (f"{'='*100 }")


if __name__ =="__main__":
    main ()
